package com.forestry.counter.domain.usecase.florist

// ═══════════════════════════════════════════════════════════════════════════════
//  FloristDatabaseExtension2.kt — espèces complémentaires (arbres, arbustes,
//  herbacées, hygrophiles, méditerranéennes)
//  Sources : Flora Gallica, INPN, valeurs d'Ellenberg France.
// ═══════════════════════════════════════════════════════════════════════════════

internal object FloristDatabaseExtension2 {

    private val D = FloristDatabase

    val SPECIES: List<EspeceVegetale> = listOf(

        // ── ARBRES ────────────────────────────────────────────────────────────

        EspeceVegetale("QUERCUS_ILEX",
            D.tx("Quercus ilex","L.","Fagaceae","Quercus","ilex","Chêne vert",
                listOf("Yeuse","Chêne des garrigues"), listOf("Quercus gramuntia")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime dense arrondie","10–20 m","Chêne méditerranéen à feuilles persistantes",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Persistantes, coriaces, 3–7 cm, dessus brillant, dessous gris tomenteux",
                "Chatons mâles","Jaune","Mars–Avril",
                TypeFruit.GLAND, ModeDispersion.ZOOCHORE,"Octobre–Novembre",
                "Pivotant profond","Glands allongés"),
            D.ec(1,2,3, 1,2,3, 6.0,7.5,8.5, true, false, NiveauLumiere.PLEIN_SOLEIL, 1000,-15.0,
                listOf("calcaire"), listOf("Méditerranéen")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.BASOPHILE,
                sig="Indicateur de climat méditerranéen thermophile et xérophile."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.LISIERE), listOf(TypeMilieu.MILIEU_ROCHEUX),
                listOf("Yeusaie","Garrigue arborée"), listOf("Quercion ilicis")),
            D.dist("Région méditerranéenne","Commun dans le Midi",
                listOf("Occitanie","PACA","Corse")),
            D.phen(listOf(3,4), listOf(10,11), "300–500 ans"),
            Interactions(listOf("Pistacia lentiscus"), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Médiocre — bois de feu dense",
                listOf("Chauffage"), 2, 5)),

        EspeceVegetale("CASTANEA_SATIVA",
            D.tx("Castanea sativa","Mill.","Fagaceae","Castanea","sativa","Châtaignier commun",
                listOf("Châtaignier","Arbre à pain"), listOf("Castanea vulgaris")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime large étalée","20–35 m","Bois tanifère résistant à la pourriture",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "10–25 cm, dentées, lancéolées-oblongues, glabres",
                "Chatons dressés allongés","Blanc-crème","Juin–Juillet",
                TypeFruit.NOIX, ModeDispersion.ZOOCHORE,"Octobre",
                "Pivotant puissant, rejet vigoureux","Bogue épineuse 2–3 châtaignes"),
            D.ec(2,3,4, 2,3,4, 4.5,5.5,6.5, false, false, NiveauLumiere.LUMIERE_PARTIELLE, 1500,-20.0,
                listOf("sablo-limoneuse acide"), listOf("Atlantique","Sub-méditerranéen")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDOPHILE,
                sig="Indicateur de sol siliceux acide. Évite calcaire et engorgement."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                listOf("Châtaigneraie"), listOf("Quercion pubescenti-petraeae")),
            D.dist("Europe méridionale","Très commun Massif Central, Sud-Ouest, Ardèche, Corse",
                listOf("Auvergne-Rhône-Alpes","Occitanie","Nouvelle-Aquitaine","Corse")),
            D.phen(listOf(6,7), listOf(10), "500–1000 ans"),
            Interactions(emptyList(), mycorhizes = listOf("Boletus edulis","Cantharellus cibarius"),
                planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Très bonne — classe 2 naturelle",
                listOf("Palissade","Tonnellerie","Parquet"), 3, 2,
                "Sensible chancre", listOf("Cryphonectria parasitica"), 4, "Taillis 25–35 ans")),

        EspeceVegetale("TAXUS_BACCATA",
            D.tx("Taxus baccata","L.","Taxaceae","Taxus","baccata","If commun",
                listOf("If d'Europe")),
            D.cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE,
                StatutIndigene.INDIGENE, StatutInvasif.NON_INVASIVE, StatutProtection.ASSEZ_COMMUNE),
            D.morph("Conique à colonnaire","5–15 m","TOUTES PARTIES TOXIQUES sauf arille rouge",
                TypeFeuille.AIGUILLE, DispositionFeuille.ALTERNEE,
                "Aiguilles plates 1–3 cm, vert foncé dessus, pâle dessous",
                "Fleurs unisexuées discrètes","Verdâtre","Février–Avril",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Août–Octobre",
                "Pivot dense","Arille rouge translucide"),
            D.ec(2,3,4, 2,3,4, 5.5,7.0,8.5, true, false, NiveauLumiere.PLEIN_OMBRE, 1500,-30.0,
                listOf("calcaire"), listOf("Montagnard")),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.BASOPHILE,
                sig="Indicateur de sols calcaires frais et ombragés. Sciaphile strict."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.MILIEU_ROCHEUX),
                listOf("Hêtraie à if"), listOf("Fagion sylvaticae")),
            D.dist("Europe et Asie Mineure","Dispersé, rare en plaine",
                listOf("Normandie","Alpes","Pyrénées","Jura")),
            D.phen(listOf(2,3,4), listOf(8,9,10), "1000–3000 ans"),
            Interactions(listOf("Fagus sylvatica"), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Très dense, précieux",
                listOf("Lutherie","Arc"), 3, 5)),

        EspeceVegetale("ULMUS_MINOR",
            D.tx("Ulmus minor","Mill.","Ulmaceae","Ulmus","minor","Orme champêtre",
                listOf("Orme lisse"), listOf("Ulmus carpinifolia")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime ovale","20–30 m","Décimé par la graphiose depuis les années 1970",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Asymétriques, doublement dentées, 6–12 cm, rudes",
                "Fascicules rougeâtres","Rouge-violet","Février–Mars",
                TypeFruit.SAMARE, ModeDispersion.ANEMOCHORE,"Avril–Mai",
                "Traçant","Samare elliptique"),
            D.ec(2,3,4, 3,4,5, 6.5,7.5,8.5, true, false, NiveauLumiere.LUMIERE_PARTIELLE, 800,-25.0,
                listOf("argile","limon-argileux"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur de sol fertile, frais, souvent alluvionnaire."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.RIPISYLVE), listOf(TypeMilieu.LISIERE),
                listOf("Ormaie","Frênaie-ormaie"), listOf("Ulmion minoris")),
            D.dist("Europe et Asie occidentale","Autrefois commun, rare aujourd'hui (graphiose)",
                listOf("Toute la France, bords de routes")),
            D.phen(listOf(2,3), listOf(4,5), "150–200 ans"),
            Interactions(emptyList(), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Excellente — ébénisterie",
                listOf("Ébénisterie","Charronnage"), 3, 3,
                "TRÈS sensible graphiose", listOf("Ophiostoma ulmi"), 3)),

        EspeceVegetale("SALIX_ALBA",
            D.tx("Salix alba","L.","Salicaceae","Salix","alba","Saule blanc",
                listOf("Osier blanc","Saule argenté")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime large, rameaux pendants argentés","20–25 m","Pousse rapide, tronc strié",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Lancéolées, 5–10 cm, soyeuses argentées",
                "Chatons dressés","Jaune","Avril",
                TypeFruit.CAPSULE, ModeDispersion.ANEMOCHORE,"Mai–Juin",
                "Traçant, drageons","Graines cotonneuses"),
            D.ec(4,5,6, 3,4,5, 6.0,7.0,8.0, true, true, NiveauLumiere.PLEIN_SOLEIL, 1000,-30.0,
                listOf("alluvionnaire"), listOf("Plaine alluviale")),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro = true, sig="INDICATEUR de sol inondable, berges de cours d'eau."),
            D.hab(listOf(TypeMilieu.RIPISYLVE), listOf(TypeMilieu.FORET_FEUILLUE),
                listOf("Saulaie"), listOf("Salicion albae")),
            D.dist("Eurasie","Commun sur toutes les berges",
                listOf("Toute la France, plaines alluviales")),
            D.phen(listOf(4), listOf(5,6), "80–150 ans"),
            Interactions(emptyList(), planteMellifere = true, planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible",
                listOf("Vannerie","Pâte à papier"), 5, 2)),

        EspeceVegetale("ROBINIA_PSEUDOACACIA",
            D.tx("Robinia pseudoacacia","L.","Fabaceae","Robinia","pseudoacacia","Robinier faux-acacia",
                listOf("Acacia","Faux-acacia")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE,
                StatutIndigene.NEOPHYTE, StatutInvasif.ENVAHISSANTE_MAJEURE),
            D.morph("Cime irrégulière, rameaux épineux","20–25 m","Fixateur d'azote, bois très durable",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "9–19 folioles ovales, 2–5 cm, glabres",
                "Grappes pendantes 10–20 cm","Blanc","Mai–Juin",
                TypeFruit.SILIQUE, ModeDispersion.ZOOCHORE,"Septembre–Octobre",
                "Traçant envahissant","Stipules en épines, gousse aplatie"),
            D.ec(1,2,3, 2,3,4, 5.0,6.5,8.0, false, false, NiveauLumiere.PLEIN_SOLEIL, 1200,-30.0,
                listOf("sableuse","caillouteuse"), listOf("Continental","Atlantique")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.ACIDICLINE,
                fert = true, perturb = true, sig="INVASIVE MAJEURE. Nitrifie le sol. Indicateur sol perturbé."),
            D.hab(listOf(TypeMilieu.LISIERE), listOf(TypeMilieu.FORET_FEUILLUE),
                emptyList(), emptyList()),
            D.dist("Amérique du Nord (XVIIe)","Commun toute la France — fortement invasif",
                listOf("Partout")),
            D.phen(listOf(5,6), listOf(9,10), "100–200 ans"),
            Interactions(emptyList(), planteMellifere = true),
            D.if_(RoleForestier.ESSENCE_PIONNIERE,"Excellente — classe 1 naturelle",
                listOf("Poteaux","Palissade"), 1, 2)),

        EspeceVegetale("SORBUS_AUCUPARIA",
            D.tx("Sorbus aucuparia","L.","Rosaceae","Sorbus","aucuparia","Sorbier des oiseleurs",
                listOf("Sorbier sauvage","Cochène")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime ovale claire","10–15 m","Baies rouges, forêts montagnardes",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "13–17 folioles dentées 3–6 cm",
                "Corymbe blanc","Blanc","Mai–Juin",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Août–Septembre",
                "Fibreux peu profond","Baies rouges en grappes"),
            D.ec(2,3,4, 1,2,3, 4.0,5.5,7.0, false, false, NiveauLumiere.LUMIERE_PARTIELLE, 2200,-40.0,
                listOf("acide"), listOf("Montagnard","Sub-alpin")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                sig="Indicateur de sol acide montagnard. Pionnière des coupes en altitude."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_RESINEUSE), listOf(TypeMilieu.LISIERE),
                listOf("Hêtraie montagnarde"), listOf("Vaccinio-Piceion")),
            D.dist("Europe boréale et montagneuse","Commun massifs montagnards",
                listOf("Vosges","Alpes","Pyrénées","Massif Central")),
            D.phen(listOf(5,6), listOf(8,9), "80–100 ans"),
            Interactions(listOf("Picea abies"), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible",emptyList(), 4, 4)),

        EspeceVegetale("JUGLANS_REGIA",
            D.tx("Juglans regia","L.","Juglandaceae","Juglans","regia","Noyer commun",
                listOf("Noyer royal"), emptyList()),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE,
                StatutIndigene.ARCHAEOPHYTE),
            D.morph("Cime large étalée","25–30 m","Bois de haute valeur, feuilles aromatiques",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "5–9 folioles ovales 8–15 cm, odeur caractéristique",
                "Chatons mâles","Verdâtre","Avril–Mai",
                TypeFruit.NOIX, ModeDispersion.ZOOCHORE,"Octobre",
                "Pivotant profond","Drupe verte, noix à coque dure"),
            D.ec(2,3,4, 3,4,5, 6.0,7.5,8.5, true, false, NiveauLumiere.PLEIN_SOLEIL, 1000,-25.0,
                listOf("argilo-limoneuse"), listOf("Sub-méditerranéen")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur de sol profond, fertile et frais."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                emptyList(), emptyList()),
            D.dist("Asie centrale (cultivé Antiquité)","Très planté, subspontané Midi",
                listOf("Auvergne-Rhône-Alpes","Nouvelle-Aquitaine","Occitanie")),
            D.phen(listOf(4,5), listOf(10), "200 ans"),
            Interactions(emptyList(), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Exceptionnelle — ébénisterie de luxe",
                listOf("Ébénisterie","Veneer","Lutherie"), 3, 2,
                "Sensible anthracnose", listOf("Gnomonia leptostyla"), 3, "Révolution 60 ans")),

        // ── ARBUSTES / LISIÈRES ───────────────────────────────────────────────

        EspeceVegetale("CRATAEGUS_MONOGYNA",
            D.tx("Crataegus monogyna","Jacq.","Rosaceae","Crataegus","monogyna","Aubépine monogyne",
                listOf("Épine blanche","Aubépine commune")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste épineux dense","2–8 m","Haies denses, baies rouges (cenelles)",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Profondément lobées, 1–4 cm, 3–7 lobes",
                "Corymbes","Blanc","Avril–Juin",
                TypeFruit.DRUPE, ModeDispersion.ZOOCHORE,"Septembre–Novembre",
                "Traçant","Cenelles à 1 noyau"),
            D.ec(2,3,4, 2,3,4, 5.5,7.0,8.5, true, false, NiveauLumiere.PLEIN_SOLEIL, 1600,-25.0,
                listOf("calcaire"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Ubiquiste de lisière. Indicateur de haie ancienne et d'écotone stable."),
            D.hab(listOf(TypeMilieu.LISIERE), listOf(TypeMilieu.FORET_FEUILLUE),
                listOf("Haie bocagère"), listOf("Berberidion")),
            D.dist("Europe et Asie","Très commun dans toute la France",
                listOf("Toute la France")),
            D.phen(listOf(4,5,6), listOf(9,10,11), "50–100 ans"),
            Interactions(emptyList(), planteMellifere = true, planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible",listOf(), 2, 3)),

        EspeceVegetale("PRUNUS_SPINOSA",
            D.tx("Prunus spinosa","L.","Rosaceae","Prunus","spinosa","Prunellier",
                listOf("Épine noire","Prunelle sauvage")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Fourré épineux","1–4 m","Fleurs avant feuilles, prunelles bleues-noires",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Elliptiques-ovales, 2–5 cm, dentées",
                "Fleurs solitaires","Blanc pur","Mars–Avril",
                TypeFruit.DRUPE, ModeDispersion.ZOOCHORE,"Octobre–Novembre",
                "Traçant, drageons abondants","Prunelles astringentes"),
            D.ec(2,3,4, 2,3,4, 5.5,7.0,8.5, false, false, NiveauLumiere.PLEIN_SOLEIL, 1600,-30.0,
                listOf("calcaire","argile"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.NEUTROPHILE,
                perturb = true, sig="Indicateur de pelouse abandonnée en cours d'embroussaillement."),
            D.hab(listOf(TypeMilieu.LISIERE), emptyList(),
                listOf("Haie bocagère"), listOf("Berberidion")),
            D.dist("Europe et Asie","Très commun dans toute la France",
                listOf("Toute la France")),
            D.phen(listOf(3,4), listOf(10,11), "30–50 ans"),
            Interactions(emptyList(), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible",listOf(), 2, 3)),

        EspeceVegetale("HEDERA_HELIX",
            D.tx("Hedera helix","L.","Araliaceae","Hedera","helix","Lierre grimpant",
                listOf("Lierre commun","Lierre des bois")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.LIANE),
            D.morph("Liane persistante grimpante","jusqu'à 30 m","Feuilles lobées jeunes, entières adultes",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Stériles : 3–5 lobes ; fertiles : entières ovales",
                "Ombelle sphérique","Jaune-verdâtre","Septembre–Novembre",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Janvier–Mars",
                "Crampons aériens","Baies noires toxiques"),
            D.ec(2,3,4, 2,3,4, 5.5,7.0,8.5, true, false, NiveauLumiere.PLEIN_OMBRE, 1200,-25.0,
                listOf("argilo-limoneuse"), listOf("Atlantique")),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur d'ambiance forestière stable. Sciaphile."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                listOf("Chênaie-charmaie à lierre"), listOf("Carpinion")),
            D.dist("Europe et Asie","Très commun, surtout Ouest",
                listOf("Toute la France")),
            D.phen(listOf(9,10,11), listOf(1,2,3), "Persistante"),
            Interactions(emptyList(), planteMellifere = true, planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE,"Faible",listOf(), 3, 3)),

        EspeceVegetale("FRANGULA_ALNUS",
            D.tx("Frangula alnus","Mill.","Rhamnaceae","Frangula","alnus","Bourdaine",
                listOf("Nerprun bourdaine"), listOf("Rhamnus frangula")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste à rameaux grêles","1–5 m","Lenticelles blanchâtres caractéristiques",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Elliptiques, 3–7 cm, entières, nervures arquées",
                "Petites fleurs axillaires","Blanc-verdâtre","Mai–Juillet",
                TypeFruit.DRUPE, ModeDispersion.ZOOCHORE,"Juillet–Septembre",
                "Traçant peu profond","Baies passant du rouge au noir"),
            D.ec(3,4,5, 2,3,4, 4.5,5.5,6.5, false, true, NiveauLumiere.DEMI_OMBRE, 1000,-20.0,
                listOf("tourbeuse","argileuse acide"), listOf("Atlantique")),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                hydro = true, sig="INDICATEUR d'humidité et d'acidité. Caractéristique aulnaies et landes humides."),
            D.hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.LANDE), listOf(TypeMilieu.FORET_FEUILLUE),
                listOf("Aulnaie-saulaie"), listOf("Alnion glutinosae")),
            D.dist("Europe et Asie","Commun toute la France, surtout Ouest",
                listOf("Toute la France")),
            D.phen(listOf(5,6,7), listOf(7,8,9), "30–50 ans"),
            Interactions(emptyList(), planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE,"Faible",listOf(), 4, 2)),

        EspeceVegetale("CYTISUS_SCOPARIUS",
            D.tx("Cytisus scoparius","(L.) Link","Fabaceae","Cytisus","scoparius","Genêt à balais",
                listOf("Genêt commun"), listOf("Sarothamnus scoparius")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.SOUS_ARBUSTE),
            D.morph("Rameaux verts anguleux dressés","0.5–2 m","Fleurs jaunes, légumineuse fixatrice",
                TypeFeuille.COMPOSEE_PALMATISEE, DispositionFeuille.ALTERNEE,
                "Rameaux sup. : feuille unique lancéolée ; inf. : trifoliée",
                "Fleurs solitaires axillaires","Jaune vif","Avril–Juin",
                TypeFruit.SILIQUE, ModeDispersion.AUTOCHORE,"Juillet–Août",
                "Pivotant + nodules fixateurs N","Gousse à bords noirs"),
            D.ec(1,2,3, 1,2,3, 4.0,5.5,7.0, false, false, NiveauLumiere.PLEIN_SOLEIL, 1600,-20.0,
                listOf("sableuse acide"), listOf("Atlantique")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                perturb = true, sig="Indicateur de coupe forestière et sol acide pauvre."),
            D.hab(listOf(TypeMilieu.LANDE, TypeMilieu.LISIERE), listOf(TypeMilieu.FORET_FEUILLUE),
                listOf("Lande atlantique"), listOf("Sarothamnion scoparii")),
            D.dist("Europe occidentale","Très commun, surtout Bretagne et Massif Central",
                listOf("Bretagne","Normandie","Massif Central")),
            D.phen(listOf(4,5,6), listOf(7,8), "10–15 ans"),
            Interactions(emptyList(), planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE,"Faible",listOf(), 2, 1)),

        // ── HERBACÉES FORESTIÈRES ─────────────────────────────────────────────

        EspeceVegetale("ANEMONE_NEMOROSA",
            D.tx("Anemone nemorosa","L.","Ranunculaceae","Anemone","nemorosa","Anémone des bois",
                listOf("Anémone sylvie","Sylvie")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée solitaire","10–25 cm","Fleurit avant l'ombrage forestier",
                TypeFeuille.SIMPLE, DispositionFeuille.VERTICILLEE,
                "3 feuilles en verticille, palmatilobées, 3–5 lobes dentés",
                "Fleur solitaire terminale","Blanc (rose extérieur)","Mars–Avril",
                TypeFruit.AKENE, ModeDispersion.MYRMECOCHORE,"Mai–Juin",
                "Rhizome horizontal filiforme","Géophyte à floraison vernale"),
            D.ec(2,3,4, 2,3,4, 5.5,6.5,8.0, true, false, NiveauLumiere.OMBRE, 1600,-20.0,
                listOf("argilo-limoneuse"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="INDICATEUR de forêt ancienne stable. Tapis denses = continuité forestière."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Chênaie-charmaie","Hêtraie"), listOf("Carpinion","Fagion")),
            D.dist("Europe et Asie","Très commun, tapis denses en forêt ancienne",
                listOf("Toute la France")),
            D.phen(listOf(3,4), listOf(5,6), "Vivace géophyte"),
            Interactions(listOf("Fagus sylvatica","Carpinus betulus"), planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("CONVALLARIA_MAJALIS",
            D.tx("Convallaria majalis","L.","Asparagaceae","Convallaria","majalis","Muguet de mai",
                listOf("Clochette des bois","Lis des vallées")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée","15–25 cm","TOUTES PARTIES TOXIQUES",
                TypeFeuille.SIMPLE, DispositionFeuille.EN_ROSETTE,
                "2–3 feuilles basales elliptiques-lancéolées 10–20 cm",
                "Grappe de clochettes pendantes","Blanc pur","Avril–Juin",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Juillet–Août",
                "Rhizome traçant","Baies rouges toxiques"),
            D.ec(2,3,4, 2,3,4, 5.5,7.0,8.0, false, false, NiveauLumiere.DEMI_OMBRE, 1500,-30.0,
                listOf("argilo-limoneuse"), listOf("Continental","Atlantique")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur de sol frais, profond, forêt ancienne."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Hêtraie","Charmaie"), listOf("Carpinion","Fagion")),
            D.dist("Europe et Asie","Commun sauf Méditerranée",
                listOf("Toute la France")),
            D.phen(listOf(4,5,6), listOf(7,8), "Vivace"),
            Interactions(listOf("Carpinus betulus"), planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("DIGITALIS_PURPUREA",
            D.tx("Digitalis purpurea","L.","Plantaginaceae","Digitalis","purpurea","Digitale pourpre",
                listOf("Doigt de la Vierge","Gant-de-Notre-Dame")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée","60–150 cm","PLANTE TOXIQUE — espèce post-coupe",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Grandes, ovales-lancéolées, mollement poilues, décurrentes",
                "Grappe unilatérale de clochettes","Rose-pourpre tacheté","Juin–Août",
                TypeFruit.CAPSULE, ModeDispersion.ANEMOCHORE,"Août–Octobre",
                "Pivotant court","Bisannuelle, rosette la 1e année"),
            D.ec(1,2,3, 1,2,3, 4.0,5.5,7.0, false, false, NiveauLumiere.LUMIERE_PARTIELLE, 1800,-15.0,
                listOf("acide","sableuse"), listOf("Atlantique")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                perturb = true, sig="Indicateur de coupe forestière sur sol acide."),
            D.hab(listOf(TypeMilieu.LISIERE, TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Coupe forestière"), emptyList()),
            D.dist("Europe atlantique","Commun Ouest France",
                listOf("Bretagne","Normandie","Massif Central")),
            D.phen(listOf(6,7,8), listOf(8,9,10), "Bisannuelle"),
            Interactions(emptyList(), planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("EPILOBIUM_ANGUSTIFOLIUM",
            D.tx("Epilobium angustifolium","L.","Onagraceae","Epilobium","angustifolium","Épilobe en épi",
                listOf("Laurier de Saint-Antoine"), listOf("Chamerion angustifolium")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée","60–150 cm","Colonise coupes et chablis très rapidement",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Lancéolées 5–15 cm, nervure médiane pâle",
                "Grappe terminale dressée","Rose-vif","Juin–Août",
                TypeFruit.CAPSULE, ModeDispersion.ANEMOCHORE,"Août–Octobre",
                "Rhizome traçant","Graines à aigrette cotonneuse"),
            D.ec(2,3,4, 2,3,4, 4.5,6.5,7.5, false, false, NiveauLumiere.PLEIN_SOLEIL, 2200,-30.0,
                emptyList(), listOf("Boréal","Montagnard")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                perturb = true, sig="INDICATEUR de coupe forestière et incendie."),
            D.hab(listOf(TypeMilieu.LISIERE, TypeMilieu.FORET_RESINEUSE), emptyList(),
                listOf("Coupe forestière"), emptyList()),
            D.dist("Circum-boréal","Commun toute la France, surtout montagne",
                listOf("Toute la France")),
            D.phen(listOf(6,7,8), listOf(8,9,10), "Vivace"),
            Interactions(emptyList(), planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("BRACHYPODIUM_SYLVATICUM",
            D.tx("Brachypodium sylvaticum","(Huds.) P.Beauv.","Poaceae","Brachypodium","sylvaticum","Brachypode des bois",
                listOf("Brachypode sylvestre")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Touffes lâches","40–90 cm","Graminée forestière ombrophile",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Plates, 6–15 mm larges, poilues, molles, vert clair",
                "Épillet dressé à longues arêtes","Verdâtre","Juin–Août",
                TypeFruit.AKENE, ModeDispersion.BAROCHORE,"Août–Septembre",
                "Souche fibreuse","Lemmes à longues arêtes"),
            D.ec(2,3,4, 3,4,5, 5.5,7.0,8.5, true, false, NiveauLumiere.DEMI_OMBRE, 1500,-20.0,
                listOf("argilo-calcaire"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.NEUTROPHILE,
                sig="Graminée caractéristique de forêts neutrophiles fraîches."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Chênaie-charmaie","Hêtraie"), listOf("Carpinion","Fagion")),
            D.dist("Europe et Asie","Commun dans toute la France",
                listOf("Toute la France")),
            D.phen(listOf(6,7,8), listOf(8,9), "Vivace"),
            Interactions(listOf("Carpinus betulus")),
            D.if_(RoleForestier.INDICATRICE)),

        // ── ESPÈCES HYGROPHILES / ZONES HUMIDES ──────────────────────────────

        EspeceVegetale("FILIPENDULA_ULMARIA",
            D.tx("Filipendula ulmaria","(L.) Maxim.","Rosaceae","Filipendula","ulmaria","Reine-des-prés",
                listOf("Spirée ulmaire","Herbe aux abeilles"), listOf("Spiraea ulmaria")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée","80–150 cm","Odeur de miel intense",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "Grandes pennées, folioles terminales grandes 3-lobées, dessous blanchâtre",
                "Cymes denses","Crème-blanc","Juin–Août",
                TypeFruit.AKENE, ModeDispersion.BAROCHORE,"Août–Octobre",
                "Rhizome court","Akènes enroulés spirale"),
            D.ec(4,5,6, 3,4,5, 5.5,7.0,8.0, false, true, NiveauLumiere.LUMIERE_PARTIELLE, 1800,-25.0,
                listOf("alluvionnaire","tourbeuse"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro = true, sig="INDICATEUR de sol humide, prairie inondable, ripisylve."),
            D.hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.ZONE_HUMIDE), emptyList(),
                listOf("Mégaphorbiaie","Prairie humide"), listOf("Filipendulion")),
            D.dist("Eurasie","Très commun toute la France",
                listOf("Toute la France, bords de cours d'eau")),
            D.phen(listOf(6,7,8), listOf(8,9,10), "Vivace"),
            Interactions(emptyList(), planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("CALTHA_PALUSTRIS",
            D.tx("Caltha palustris","L.","Ranunculaceae","Caltha","palustris","Populage des marais",
                listOf("Souci d'eau","Populage")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HELOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige creuse étalée","20–50 cm","Fleurs jaunes brillantes printanières",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Réniformes-cordées, 5–12 cm, bord crénelé, glabres",
                "Fleurs terminales solitaires ou par 2","Jaune vif","Mars–Juin",
                TypeFruit.CAPSULE, ModeDispersion.HYDROCHORE,"Juin–Juillet",
                "Fasciculé court","TOXIQUE à l'état frais (protoanémonine)"),
            D.ec(5,6,7, 3,4,5, 5.5,7.0,8.0, false, true, NiveauLumiere.PLEIN_SOLEIL, 2400,-35.0,
                listOf("alluvionnaire","tourbeuse"), listOf("Boréal","Montagnard")),
            D.vi(IndicHumidite.HYGROPHYTE_STRICT, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro = true, sig="INDICATEUR de zones inondées en permanence. Marqueur fort d'hydromorphie."),
            D.hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Prairie marécageuse","Aulnaie inondée"), listOf("Calthion palustris")),
            D.dist("Circum-boréal","Très commun bords de ruisseaux, fossés humides",
                listOf("Toute la France")),
            D.phen(listOf(3,4,5,6), listOf(6,7), "Vivace"),
            Interactions(emptyList(), planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("IRIS_PSEUDACORUS",
            D.tx("Iris pseudacorus","L.","Iridaceae","Iris","pseudacorus","Iris des marais",
                listOf("Iris jaune","Iris faux-acore")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HELOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée ramifiée","70–120 cm","Grandes fleurs jaunes caractéristiques",
                TypeFeuille.SIMPLE, DispositionFeuille.EN_ROSETTE,
                "Ensiformes, 2–3 cm larges, vert grisâtre",
                "Fleurs grandes à 3 sépales tombants","Jaune vif","Mai–Juillet",
                TypeFruit.CAPSULE, ModeDispersion.HYDROCHORE,"Août–Septembre",
                "Rhizome épais horizontal","Capsule trigone, graines aplaties liège"),
            D.ec(5,6,7, 3,4,5, 5.5,7.5,8.5, true, true, NiveauLumiere.PLEIN_SOLEIL, 1500,-25.0,
                listOf("alluvionnaire","tourbeuse"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.HYGROPHYTE_STRICT, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro = true, sig="INDICATEUR fort de sol constamment humide à inondé."),
            D.hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Roselière","Bord de mare"), listOf("Phragmition")),
            D.dist("Europe et Asie","Très commun bords d'eau toute la France",
                listOf("Toute la France")),
            D.phen(listOf(5,6,7), listOf(8,9), "Vivace"),
            Interactions(emptyList(), planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("PHRAGMITES_AUSTRALIS",
            D.tx("Phragmites australis","(Cav.) Trin. ex Steud.","Poaceae","Phragmites","australis","Roseau commun",
                listOf("Phragmite"), listOf("Phragmites communis")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HELOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tiges hautes dressées","100–400 cm","Graminée hélophyte dominante des zones humides",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Plates, larges 1–4 cm, ligule de poils",
                "Grande panicule brune plumeuse","Brun-violacé","Août–Septembre",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Octobre–Novembre",
                "Rhizome traçant puissant","Chaume persistant l'hiver"),
            D.ec(5,6,7, 3,4,5, 5.5,7.5,8.5, true, true, NiveauLumiere.PLEIN_SOLEIL, 1200,-30.0,
                listOf("alluvionnaire","vase"), listOf("Atlantique","Continental","Méditerranéen")),
            D.vi(IndicHumidite.HYDROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro = true, sig="INDICATEUR de sol inondé ou eau stagnante peu profonde. Forme roselières."),
            D.hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Roselière"), listOf("Phragmition australis")),
            D.dist("Subcosmopolite","Très commun plans d'eau et rivières toute la France",
                listOf("Toute la France")),
            D.phen(listOf(8,9), listOf(10,11), "Vivace"),
            Interactions(emptyList(), planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("LYTHRUM_SALICARIA",
            D.tx("Lythrum salicaria","L.","Lythraceae","Lythrum","salicaria","Salicaire commune",
                listOf("Herbe aux coliques","Salicaire")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée à 4 angles","60–150 cm","Fleurs rose-pourpre estivales",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Lancéolées, 3–7 cm, sessiles, semi-amplexicaules",
                "Épis terminaux denses","Rose-pourpre vif","Juin–Septembre",
                TypeFruit.CAPSULE, ModeDispersion.HYDROCHORE,"Août–Octobre",
                "Souche ligneuse","Hétérostylie tristyle (3 types de fleurs)"),
            D.ec(4,5,6, 3,4,5, 5.5,7.5,8.5, false, true, NiveauLumiere.PLEIN_SOLEIL, 1500,-25.0,
                listOf("alluvionnaire"), listOf("Atlantique","Continental")),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro = true, sig="Indicateur de berges et prairies inondables."),
            D.hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Prairie alluviale","Mégaphorbiaie"), listOf("Filipendulion")),
            D.dist("Eurasie","Très commun bords d'eau",
                listOf("Toute la France")),
            D.phen(listOf(6,7,8,9), listOf(8,9,10), "Vivace"),
            Interactions(emptyList(), planteMellifere = true, planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE)),

        // ── ESPÈCES MÉDITERRANÉENNES ──────────────────────────────────────────

        EspeceVegetale("ARBUTUS_UNEDO",
            D.tx("Arbutus unedo","L.","Ericaceae","Arbutus","unedo","Arbousier commun",
                listOf("Arbre aux fraises","Arbousier")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste à arbrisseaux persistant","2–10 m","Fleurs et fruits simultanément en automne",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Persistantes, elliptiques, 5–10 cm, dentées, brillantes",
                "Panicules pendantes","Blanc rosé","Octobre–Décembre",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Octobre–Novembre an+1",
                "Pivotant profond","Baies sphériques rouges comestibles, granuleuses"),
            D.ec(1,2,3, 1,2,3, 4.5,6.0,8.0, false, false, NiveauLumiere.PLEIN_SOLEIL, 800,-8.0,
                listOf("siliceuse","calcaire acide"), listOf("Méditerranéen","Atlantique doux")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                sig="Indicateur de maquis et forêts méditerranéennes siliceuses."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.LANDE), emptyList(),
                listOf("Maquis","Chênaie verte"), listOf("Quercion ilicis")),
            D.dist("Méditerranée et façade atlantique","Corse, PACA, Languedoc, côtes atlantiques",
                listOf("Corse","PACA","Occitanie","Bretagne (côtes)")),
            D.phen(listOf(10,11,12), listOf(10,11), "Persistant"),
            Interactions(emptyList(), planteMellifere = true, planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible",listOf(), 2, 3)),

        EspeceVegetale("PISTACIA_LENTISCUS",
            D.tx("Pistacia lentiscus","L.","Anacardiaceae","Pistacia","lentiscus","Pistachier lentisque",
                listOf("Lentisque","Pistachier")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste touffu persistant","1–4 m","Caractéristique de la garrigue basse",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "Persistantes, 4–10 folioles elliptiques 1.5–5 cm, coriaces",
                "Grappes courtes denses","Rouge-verdâtre","Mars–Mai",
                TypeFruit.DRUPE, ModeDispersion.ZOOCHORE,"Octobre–Novembre",
                "Pivotant profond","Drupes globuleuses rouge puis noires"),
            D.ec(1,2,3, 1,2,3, 6.0,7.5,8.5, true, false, NiveauLumiere.PLEIN_SOLEIL, 600,-5.0,
                listOf("calcaire","sableuse"), listOf("Méditerranéen")),
            D.vi(IndicHumidite.XEROPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.BASOPHILE,
                sig="INDICATEUR strict de la garrigue méditerranéenne thermophile basse."),
            D.hab(listOf(TypeMilieu.LANDE, TypeMilieu.LISIERE), emptyList(),
                listOf("Garrigue","Phrygane"), listOf("Oleo-Ceratonion")),
            D.dist("Méditerranée","Littoral méditerranéen français et Corse",
                listOf("Occitanie","PACA","Corse")),
            D.phen(listOf(3,4,5), listOf(10,11), "Persistant"),
            Interactions(listOf("Quercus ilex"), planteRessourcesFaune = true),
            D.if_(RoleForestier.INDICATRICE,"Faible",listOf(), 1, 3)),

        EspeceVegetale("PINUS_HALEPENSIS",
            D.tx("Pinus halepensis","Mill.","Pinaceae","Pinus","halepensis","Pin d'Alep",
                listOf("Pin de Jérusalem")),
            D.cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime claire irrégulière","15–20 m","Pin méditerranéen résistant à la sécheresse",
                TypeFeuille.AIGUILLE, DispositionFeuille.VERTICILLEE,
                "Aiguilles par 2, fines 6–10 cm, vert clair",
                "Cônes mâles groupés","Jaunâtre","Mars–Avril",
                TypeFruit.STROBIL, ModeDispersion.ANEMOCHORE,"Septembre–Octobre an 3",
                "Pivotant profond","Cônes réfléchis persistants, sérotineux"),
            D.ec(1,2,3, 1,2,3, 6.5,7.5,8.5, true, false, NiveauLumiere.PLEIN_SOLEIL, 900,-12.0,
                listOf("calcaire"), listOf("Méditerranéen")),
            D.vi(IndicHumidite.XEROPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.BASOPHILE,
                sig="Indicateur de climat méditerranéen sec. Cônes sérotineux s'ouvrent avec la chaleur."),
            D.hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.LISIERE), emptyList(),
                listOf("Pineraie à Pin d'Alep"), listOf("Pino halepensis-Quercion")),
            D.dist("Région méditerranéenne","Très commun garrigue et arrière-pays méditerranéen",
                listOf("PACA","Occitanie","Corse")),
            D.phen(listOf(3,4), listOf(9,10), "150 ans"),
            Interactions(emptyList()),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Médiocre",
                listOf("Pâte à papier"), 1, 4))
    )
}
