package com.forestry.counter.domain.usecase.florist

// ═══════════════════════════════════════════════════════════════════════════════
//  FloristDatabase.kt — Référentiel espèces végétales françaises
//  Sources : Flora Gallica, valeurs d'Ellenberg, indices de Landolt
// ═══════════════════════════════════════════════════════════════════════════════

object FloristDatabase {

    fun findById(id: String): EspeceVegetale? = species.find { it.id == id }
    fun findByNomFrancais(nom: String): EspeceVegetale? =
        species.find { it.taxonomie.nomFrancais.contains(nom, ignoreCase = true) }
    fun findIndicatrices(milieu: TypeMilieu): List<EspeceVegetale> =
        species.filter { milieu in it.habitat.milieuxPrincipaux }

    fun diagnostiquerFlore(ids: List<String>): DiagnosticFloristique {
        val obs = ids.mapNotNull { findById(it) }
        if (obs.isEmpty()) return DiagnosticFloristique(
            especesObservees = ids, gradientHydriqueDeduît = 3.0, gradientFertiliteDeduît = 3.0,
            indicateurAcidite = IndicAcidite.NEUTROPHILE, probabiliteHydromorphie = 0.0,
            probabiliteCompaction = 0.0, probabilitePerturbation = 0.0,
            especesIndicatricesCles = emptyList(), interpretationTextuelle = "Aucune espèce reconnue."
        )
        val meanH = obs.map { it.valeurIndicatrice.ellenbergH.codeEllenberg }.average()
        val meanN = obs.map { it.valeurIndicatrice.ellenbergN.codeEllenberg }.average()
        val domR  = obs.groupingBy { it.valeurIndicatrice.ellenbergR }.eachCount().maxByOrNull { it.value }?.key ?: IndicAcidite.NEUTROPHILE
        val probHydro   = obs.count { it.valeurIndicatrice.indicateurHydromorphie   }.toDouble() / obs.size
        val probCompact = obs.count { it.valeurIndicatrice.indicateurCompaction      }.toDouble() / obs.size
        val probPerturb = obs.count { it.valeurIndicatrice.indicateurPerturbation   }.toDouble() / obs.size
        val cles = obs.filter { it.valeurIndicatrice.indicateurHydromorphie || it.valeurIndicatrice.indicateurPerturbation ||
            it.valeurIndicatrice.ellenbergH.codeEllenberg >= 5 || it.valeurIndicatrice.ellenbergN.codeEllenberg >= 5 ||
            it.valeurIndicatrice.ellenbergR == IndicAcidite.ACIDOPHILE_STRICT }
        val interp = buildString {
            append("${obs.size} esp. : H≈${String.format("%.1f", meanH)}/7, N≈${String.format("%.1f", meanN)}/6, R=${domR.labelFr}. ")
            if (probHydro > 0.3) append("⚠ Hydromorphie probable (${(probHydro*100).toInt()}% hygrophytes). ")
            if (probPerturb > 0.3) append("⚠ Flore perturbée/nitrophile. ")
            if (probCompact > 0.3) append("⚠ Indicateurs de compaction. ")
        }
        return DiagnosticFloristique(ids, meanH, meanN, domR, probHydro, probCompact, probPerturb, cles, interp)
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    internal fun tx(sci: String, auteur: String, famille: String, genre: String, esp: String,
                   fr: String, vern: List<String> = emptyList(), syn: List<String> = emptyList()) =
        Taxonomie(sci, auteur, famille, genre, esp, synonymes = syn, nomFrancais = fr, nomsVernaculaires = vern)

    internal fun cl(g: GroupeBiologique, t: TypeBiologique, s: StrateVegetale,
                   i: StatutIndigene = StatutIndigene.INDIGENE,
                   inv: StatutInvasif = StatutInvasif.NON_INVASIVE,
                   prot: StatutProtection = StatutProtection.COMMUNE) = Classification(g, t, s, i, inv, prot)

    internal fun ec(hMin: Int, hOpt: Int, hMax: Int, nMin: Int, nOpt: Int, nMax: Int,
                   phMin: Double = 4.0, phOpt: Double = 6.0, phMax: Double = 7.5,
                   calcaire: Boolean = false, hydro: Boolean = false,
                   lumiere: NiveauLumiere = NiveauLumiere.DEMI_OMBRE,
                   altMax: Int = 1200, froid: Double = -25.0,
                   textures: List<String> = emptyList(), climats: List<String> = emptyList()) =
        EcologieStation(hMin, hOpt, hMax, nMin, nOpt, nMax, phMin, phOpt, phMax, calcaire, hydro,
            textures, 20, lumiere, 0, 300, altMax, froid, false, climats)

    internal fun vi(h: IndicHumidite, n: IndicFertilite, r: IndicAcidite,
                   hydro: Boolean = false, perturb: Boolean = false, compac: Boolean = false, fert: Boolean = false,
                   sig: String = "") = ValeurIndicatrice(h, n, r, perturb, compac, fert, hydro, sig)

    internal fun hab(p: List<TypeMilieu>, s: List<TypeMilieu> = emptyList(),
                    assoc: List<String> = emptyList(), alli: List<String> = emptyList(),
                    desc: String = "") = Habitat(p, s, assoc, alli, descriptionHabitat = desc)

    internal fun dist(aire: String, france: String, regions: List<String> = emptyList()) =
        Distribution(aire, "", repartitionFrance = france, regionsEcologiquesFR = regions)

    internal fun phen(flor: List<Int>, fruct: List<Int> = emptyList(), vie: String = "Vivace") =
        Phenologie(moisFloraison = flor, moisFructification = fruct, dureeDeVie = vie)

    internal fun morph(port: String, taille: String, desc: String,
                      tf: TypeFeuille, df: DispositionFeuille, dfDesc: String,
                      inflo: String, coulFleur: String, florPeriode: String,
                      fruit: TypeFruit, disp: ModeDispersion, fructPeriode: String,
                      racine: String, extra: String = "") =
        Morphologie(port, taille, desc, tf, df, dfDesc, inflo, coulFleur, florPeriode, fruit, disp, fructPeriode, racine, extra)

    internal fun if_(role: RoleForestier, bois: String = "", usage: List<String> = emptyList(),
                    seche: Int = 3, gel: Int = 3, mal: String = "",
                    maladies: List<String> = emptyList(), vent: Int = 3, prod: String = "") =
        ImportanceForestiere(role, bois, usage, seche, gel, 3, 3, mal, maladies, vent, prod)

    // ═══════════════════════════════════════════════════════════════════════════
    //  LISTE DES ESPÈCES
    // ═══════════════════════════════════════════════════════════════════════════

    val species: List<EspeceVegetale> get() = CORE_SPECIES + FloristDatabaseExtension.SPECIES

    private val CORE_SPECIES: List<EspeceVegetale> = listOf(

        // ── ARBRES FEUILLUS ────────────────────────────────────────────────────

        EspeceVegetale("QUERCUS_ROBUR",
            tx("Quercus robur","L.","Fagaceae","Quercus","robur","Chêne pédonculé",
                listOf("Chêne commun"), listOf("Quercus pedunculata")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime large irrégulière","20–40 m","Arbre caducifolié, longévité > 1000 ans, écorce crevassée.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Obovales, 5–7 lobes arrondis, base auriculée, pétiole court <1 cm.",
                "Chatons mâles pendants, fleurs femelles en épis","Verdâtre","Avril–Mai",
                TypeFruit.GLAND, ModeDispersion.ZOOCHORE,"Septembre–Novembre",
                "Pivotant profond puis étalé jusqu'à 40 m","Glands sur pédoncule long 3–8 cm"),
            ec(2,3,4, 2,3,5, 4.5,5.5,7.5, false, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 800, -25.0,
                listOf("argileuse","argilo-limoneuse"), listOf("Océanique","Semi-océanique")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Sols frais argileux, tendance acidicline, tolère engorgements temporaires."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.RIPISYLVE, TypeMilieu.ZONE_HUMIDE),
                listOf("Chênaie-charmaie","Chênaie-frênaie"), listOf("Carpinion betuli")),
            dist("Europe occidentale et centrale","Très commun, toute la France",
                listOf("Plaines","Aquitaine","Bassin Parisien","Massif Central")),
            phen(listOf(4,5), listOf(9,10,11), "500–1000 ans"),
            Interactions(listOf("Carpinus betulus","Fraxinus excelsior"),
                mycorhizes = listOf("Boletus edulis","Amanita rubescens"),
                planteRessourcesFaune = true,
                parasitesConnus = listOf("Erysiphe alphitoides (oïdium)","Thaumetopoea processionea")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Très élevée — bois d'œuvre",
                listOf("Charpente","Tonnellerie","Parquet"), 3, 2,
                "Sensible oïdium et scolytes", listOf("Erysiphe alphitoides"), 4, "Futaie 200 ans")),

        EspeceVegetale("QUERCUS_PETRAEA",
            tx("Quercus petraea","(Matt.) Liebl.","Fagaceae","Quercus","petraea","Chêne sessile",
                listOf("Chêne rouvre"), listOf("Quercus sessiliflora")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Fût élancé, cime moins étalée que Q. robur","25–40 m","Plus adapté aux terrains secs et acides.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Lobées (5–7 paires), base cunéiforme non auriculée, pétiole long 1–2 cm.",
                "Chatons mâles pendants","Verdâtre","Avril–Mai",
                TypeFruit.GLAND, ModeDispersion.ZOOCHORE,"Septembre–Octobre",
                "Pivotant très profond","Glands sessiles ou à pédoncule très court"),
            ec(1,2,3, 1,2,4, 3.5,5.0,6.5, false, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1200, -25.0,
                listOf("sablo-limoneuse","graveleuse"), listOf("Semi-océanique","Continental")),
            vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                sig="Sols bien drainés, acides. Évite les sols lourds et engorgés."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE, TypeMilieu.MILIEU_ROCHEUX),
                listOf("Chênaie sessile acidiphile"), listOf("Quercion robori-petraeae")),
            dist("Europe centro-occidentale","Très commun sur sols siliceux",
                listOf("Massif Central","Ardennes","Vosges","Landes","Bretagne")),
            phen(listOf(4,5), listOf(9,10), "400–800 ans"),
            Interactions(listOf("Betula pendula","Luzula luzuloides"), mycorhizes = listOf("Pisolithus arhizus","Lactarius quietus")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Élevée — charpente, merrain",
                listOf("Charpente","Tonnellerie","Menuiserie"), 2, 2, "", emptyList(), 5, "Futaie 180–250 ans")),

        EspeceVegetale("FAGUS_SYLVATICA",
            tx("Fagus sylvatica","L.","Fagaceae","Fagus","sylvatica","Hêtre commun",
                listOf("Fayard","Hêtre de nos forêts")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime ovoïde dense, fût lisse argenté","25–40 m","Dominant des forêts tempérées fraîches. Écorce lisse grise.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Elliptiques, bord ondulé-cilié, 7–9 paires de nervures. Roussissement automnal.",
                "Chatons globuleux","Verdâtre","Avril–Mai",
                TypeFruit.FAÎNE, ModeDispersion.ZOOCHORE,"Septembre–Octobre",
                "Superficiel étalé — sensible compaction","Faînes triangulaires dans cupule 4-lobée"),
            ec(2,3,4, 2,3,4, 4.0,5.5,7.0, true, false,
                NiveauLumiere.DEMI_OMBRE, 1800, -25.0,
                listOf("limoneuse","limon-argileuse"), listOf("Sub-montagnard","Montagnard")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Sol frais profond bien drainé. Évite l'hydromorphie. Climat frais et humide."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE), listOf(TypeMilieu.MONTAGNARD),
                listOf("Hêtraie-chênaie","Hêtraie calcicole","Hêtraie acidiphile"),
                listOf("Fagion sylvaticae","Luzulo-Fagion")),
            dist("Europe centrale et occidentale","Commun dans les massifs montagneux, absent plaine méridionale",
                listOf("Vosges","Jura","Alpes","Pyrénées","Massif Central","Normandie")),
            phen(listOf(4,5), listOf(9,10), "200–400 ans"),
            Interactions(listOf("Abies alba","Oxalis acetosella"), mycorhizes = listOf("Lactarius blennius","Russula mairei"),
                parasitesConnus = listOf("Nectria coccinea")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Élevée — bois homogène dur",
                listOf("Chauffage","Parquet","Ameublement"), 4, 3,
                "Sensible sécheresse et chablis", emptyList(), 2, "Révolution 100–150 ans")),

        EspeceVegetale("CARPINUS_BETULUS",
            tx("Carpinus betulus","L.","Betulaceae","Carpinus","betulus","Charme commun",
                listOf("Charmille")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime ovoïde dense, fût cannelé musculeux","10–25 m","Arbre dominé de la chênaie-charmaie. Bois très dur.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Ovales doublement dentées, 11–15 paires de nervures saillantes.",
                "Chatons pendants","Verdâtre","Avril–Mai",
                TypeFruit.AUTRE, ModeDispersion.ANEMOCHORE,"Août–Octobre",
                "Traçant adapté aux sols argileux compacts","Écorce grise avec nervures sinueuses. Marcescence."),
            ec(2,3,4, 2,3,4, 4.5,6.0,7.5, true, false,
                NiveauLumiere.OMBRE, 1200, -28.0, listOf("argileuse","argilo-limoneuse"),
                listOf("Semi-océanique","Continental modéré")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Sol frais à fertilité moyenne, tendance neutre. Chênaie-charmaie typique."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE, TypeMilieu.TALUS_HAIES),
                listOf("Chênaie-charmaie"), listOf("Carpinion betuli")),
            dist("Europe centrale et occidentale","Commun en plaine, absent Alpes internes et midi méditerranéen",
                listOf("Bassin Parisien","Normandie","Lorraine")),
            phen(listOf(4,5), listOf(9,10), "150–300 ans"),
            Interactions(listOf("Quercus robur","Primula elatior"), mycorhizes = listOf("Tuber aestivum")),
            if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Outillage, chauffage",
                listOf("Outillage","Maillet","Chauffage"), 3, 1, "", emptyList(), 4)),

        EspeceVegetale("FRAXINUS_EXCELSIOR",
            tx("Fraxinus excelsior","L.","Oleaceae","Fraxinus","excelsior","Frêne élevé",
                listOf("Frêne commun")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Arbre élancé, cime claire, rameaux gros","20–40 m","Arbre des milieux frais à humides. Bourgeons noirs caractéristiques.",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.OPPOSEE,
                "Imparipennées, 7–13 folioles lancéolées dentées. Chute précoce en automne.",
                "Panicules denses avant les feuilles","Violacé-verdâtre","Mars–Avril",
                TypeFruit.SAMARE, ModeDispersion.ANEMOCHORE,"Octobre–Novembre",
                "Superficiel étalé adapté aux sols humides","Bourgeons noirs veloutés distinctifs"),
            ec(3,4,5, 3,4,5, 5.5,7.0,8.0, true, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 1400, -25.0,
                listOf("alluvionnaire","limoneuse"), listOf("Semi-océanique","Continental modéré")),
            vi(IndicHumidite.HYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Sols frais à humides, riches et neutres à basiques. Fonds de vallon, berges, alluvions fertiles."),
            hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.ZONE_HUMIDE, TypeMilieu.FORET_FEUILLUE),
                emptyList(), listOf("Frênaie-aulnaie"), listOf("Alno-Ulmion")),
            dist("Europe centrale et occidentale","Très commun sauf zone méditerranéenne",
                listOf("Toute la France tempérée","Vallées alpines","Pyrénées")),
            phen(listOf(3,4), listOf(10,11), "100–250 ans"),
            Interactions(listOf("Alnus glutinosa","Filipendula ulmaria"),
                parasitesConnus = listOf("Hymenoscyphus fraxineus (chalarose — maladie mortelle)")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Très élevée — bois élastique",
                listOf("Outillage","Sports","Ameublement"), 4, 3,
                "TRÈS sensible chalarose", listOf("Chalarose (Hymenoscyphus fraxineus)"), 3, "Révolution 60–80 ans")),

        EspeceVegetale("ALNUS_GLUTINOSA",
            tx("Alnus glutinosa","(L.) Gaertn.","Betulaceae","Alnus","glutinosa","Aulne glutineux",
                listOf("Aulne noir","Vergne","Verne")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Arbre moyen à cime irrégulière, souvent multi-troncs","15–25 m","Arbre des zones inondables, nodules racinaires fixateurs d'azote.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Arrondies-obovales, apex émarginé (en creux), doublement denté. Glutineux jeunes.",
                "Chatons mâles pendants, femelles ovales","Brun-rouge","Février–Avril",
                TypeFruit.AUTRE, ModeDispersion.HYDROCHORE,"Octobre–Novembre",
                "Profond avec nodules Frankia (fixation N₂)","Strobiles ligneux persistants. Feuilles à apex émarginé caractéristique."),
            ec(4,5,5, 3,4,5, 4.5,6.5,8.0, true, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 1200, -25.0,
                listOf("alluvionnaire","tourbeux"), listOf("Océanique","Semi-océanique")),
            vi(IndicHumidite.HYDROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro=true, sig="INDICATEUR STRICT d'hydromorphie. Présence = sol inondé ou nappe permanente."),
            hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.ZONE_HUMIDE), emptyList(),
                listOf("Aulnaie-frênaie alluviale"), listOf("Alno-Ulmion","Alnion glutinosae")),
            dist("Europe, Asie Mineure","Commun sur tout le territoire sauf haute montagne",
                listOf("Toutes les vallées alluviales")),
            phen(listOf(2,3,4), listOf(10,11), "100–200 ans"),
            Interactions(listOf("Fraxinus excelsior","Filipendula ulmaria"),
                parasitesConnus = listOf("Phytophthora alni")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Bois résistant sous eau",
                listOf("Pilotis","Menuiserie humide"), 5, 2,
                "Phytophthora alni", listOf("Phytophthora alni"), 3)),

        EspeceVegetale("BETULA_PENDULA",
            tx("Betula pendula","Roth","Betulaceae","Betula","pendula","Bouleau verruqueux",
                listOf("Bouleau blanc"), listOf("Betula verrucosa")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Branches pendantes gracieuses, écorce blanc-argenté","15–25 m","Arbre pionnier léger, écorce blanche très distinctive.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Triangulaires-rhomboïdes, doublement dentées, base tronquée. Glabres et luisantes.",
                "Chatons pendants","Verdâtre","Avril–Mai",
                TypeFruit.SAMARE, ModeDispersion.ANEMOCHORE,"Juillet–Septembre",
                "Superficiel et traçant","Écorce blanche en bandelettes, rameaux verruqueux"),
            ec(1,2,4, 1,2,4, 3.5,5.0,7.0, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 1800, -35.0,
                listOf("sableuse","graveleuse"), listOf("Continental","Sub-montagnard")),
            vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                perturb=true, sig="Indicateur de sol acide peu fertile. Espèce pionnière après perturbation."),
            hab(listOf(TypeMilieu.LISIERE, TypeMilieu.LANDE, TypeMilieu.MILIEU_PERTURBE),
                listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.MONTAGNARD),
                listOf("Boulaie acidiphile")),
            dist("Eurasie boréale et tempérée","Commun partout sur sols acides",
                listOf("Landes","Massif Central","Vosges","Bretagne")),
            phen(listOf(4,5), listOf(7,8,9), "80–120 ans"),
            Interactions(listOf("Pinus sylvestris","Deschampsia flexuosa"),
                mycorhizes = listOf("Amanita muscaria","Paxillus involutus")),
            if_(RoleForestier.ESSENCE_PIONNIERE,"Chauffage, contreplaqué",
                listOf("Chauffage","Contreplaqué","Papier"), 2, 1, "", emptyList(), 2)),

        EspeceVegetale("ACER_PSEUDOPLATANUS",
            tx("Acer pseudoplatanus","L.","Sapindaceae","Acer","pseudoplatanus","Érable sycomore",
                listOf("Sycomore","Faux platane")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime large arrondie, écorce se détachant en plaques","20–35 m","Arbre de vallon frais et fertile. Colonisateur vigoureux.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Palmatilobées à 5 lobes, grandes (10–20 cm), vert foncé dessus, glauque dessous.",
                "Racèmes pendants","Jaune-verdâtre","Avril–Mai",
                TypeFruit.SAMARE, ModeDispersion.ANEMOCHORE,"Septembre–Octobre",
                "Pivotant puis traçant, adapté aux pentes","Samares à ailes étalées à 90°"),
            ec(2,3,4, 3,4,5, 5.0,6.5,8.0, true, false,
                NiveauLumiere.DEMI_OMBRE, 1800, -25.0,
                listOf("limoneuse","argilo-limoneuse"), listOf("Sub-montagnard","Montagnard")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Sol frais fertile, neutre à basique. Colonisateur des versants frais et vallons."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE, TypeMilieu.MONTAGNARD),
                listOf(TypeMilieu.LISIERE), listOf("Érablaie de vallon","Hêtraie-érablaie")),
            dist("Europe centrale et méridionale","Commun dans les massifs, plaine et montagne",
                listOf("Alpes","Pyrénées","Vosges","Massif Central")),
            phen(listOf(4,5), listOf(9,10), "200–300 ans"),
            Interactions(listOf("Fagus sylvatica","Fraxinus excelsior")),
            if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Ébénisterie, lutherie",
                listOf("Ébénisterie","Lutherie","Tournage"), 3, 3)),

        EspeceVegetale("PINUS_SYLVESTRIS",
            tx("Pinus sylvestris","L.","Pinaceae","Pinus","sylvestris","Pin sylvestre",
                listOf("Pin de Riga","Pin d'Écosse")),
            cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime irrégulière aplatie en vieux sujets, écorce rouge-orangé en haut","20–35 m","Résineux pionnier xérophile. Écorce rouge orangé caractéristique dans la couronne.",
                TypeFeuille.AIGUILLE, DispositionFeuille.OPPOSEE,
                "Aiguilles par 2, torsadées, bleu-vert glauque, 4–7 cm.",
                "Cônes mâles jaunes, femelles rouges","Jaune / Rouge","Avril–Juin",
                TypeFruit.STROBIL, ModeDispersion.ANEMOCHORE,"Automne 2e année",
                "Pivotant profond puis latéral, excellente résistance sécheresse",
                "Écorce bicolore : gris écailleux bas, rouge-orangé haut"),
            ec(1,2,3, 1,2,3, 3.5,5.0,7.0, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 2400, -40.0,
                listOf("sableuse","graveleuse"), listOf("Continental","Semi-continental")),
            vi(IndicHumidite.XEROPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                sig="Indicateur de sol acide pauvre et sec. Landes, sables. Risque dépérissement climatique en plaine."),
            hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.LANDE),
                listOf(TypeMilieu.MONTAGNARD, TypeMilieu.MILIEU_ROCHEUX),
                listOf("Pinède sylvestre xérophile"), listOf("Dicrano-Pinion")),
            dist("Du Portugal à la Sibérie","Très commun planté en plaine, naturel en montagne",
                listOf("Landes","Sologne","Fontainebleau","Alpes","Pyrénées","Massif Central")),
            phen(listOf(4,5,6), listOf(10,11), "150–300 ans (montagne > 500 ans)"),
            Interactions(listOf("Calluna vulgaris","Deschampsia flexuosa"),
                mycorhizes = listOf("Suillus bovinus","Lactarius rufus"),
                parasitesConnus = listOf("Armillaria mellea","Ips sexdentatus")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Bois résineux courant",
                listOf("Charpente légère","Palettes","Pâte à papier"), 3, 1,
                "Armillaire, scolytes", listOf("Armillaria mellea","Ips sexdentatus"), 3, "Classe 2-3")),

        EspeceVegetale("ABIES_ALBA",
            tx("Abies alba","Mill.","Pinaceae","Abies","alba","Sapin pectiné",
                listOf("Sapin blanc","Sapin des Vosges")),
            cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime pyramidale puis en cigogne âgé","30–50 m","Grand résineux montagnard. Aiguilles pectinées face blanche. Cône érigé.",
                TypeFeuille.AIGUILLE, DispositionFeuille.ALTERNEE,
                "Plates en peigne, face inférieure 2 bandes blanches stomatiques, apex échancré.",
                "Cônes mâles en chatons, femelles érigés verts","Jaune/Vert","Mai–Juin",
                TypeFruit.STROBIL, ModeDispersion.ANEMOCHORE,"Automne 1ère année",
                "Pivot profond jeunesse, traçant adulte","Cônes érigés se décomposant sur l'arbre"),
            ec(2,3,4, 2,3,4, 4.0,5.5,7.0, true, false,
                NiveauLumiere.OMBRE, 1800, -30.0,
                listOf("limoneuse profonde"), listOf("Sub-montagnard","Montagnard")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Station fraîche profonde à bonne réserve hydrique. Sol non compacté."),
            hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.FORET_MIXTE, TypeMilieu.MONTAGNARD),
                emptyList(), listOf("Sapinière-hêtraie"), listOf("Abieti-Piceion")),
            dist("Montagnes d'Europe centrale et méridionale","Vosges, Jura, Alpes, Massif Central, Pyrénées",
                listOf("Vosges","Jura","Alpes","Pyrénées","Massif Central")),
            phen(listOf(5,6), listOf(9,10), "300–600 ans"),
            Interactions(listOf("Fagus sylvatica","Oxalis acetosella"),
                mycorhizes = listOf("Cantharellus cibarius"),
                parasitesConnus = listOf("Heterobasidion annosum","Armillaria ostoyae")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Bois d'œuvre qualité — lutherie",
                listOf("Charpente","Menuiserie","Lutherie"), 4, 3,
                "Hétérobasidion, Armillaire", listOf("Heterobasidion annosum"), 3, "Révolution 120 ans")),

        EspeceVegetale("PICEA_ABIES",
            tx("Picea abies","(L.) H.Karst.","Pinaceae","Picea","abies","Épicéa commun",
                listOf("Épicéa de Norvège","Sapin de Noël")),
            cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Pyramidal strict, branches tombantes en vieillissant","30–50 m","Grand résineux montagnard à cône pendant. Rameaux tombants.",
                TypeFeuille.AIGUILLE, DispositionFeuille.ALTERNEE,
                "Aiguilles solitaires, tétragones, 1–2.5 cm, acérées, vert foncé luisant.",
                "Cônes mâles rouges, femelles pendants érigés","Rouge / Vert","Avril–Mai",
                TypeFruit.STROBIL, ModeDispersion.ANEMOCHORE,"Automne 1ère année",
                "Superficiel — très sensible chablis","Cônes pendants intacts tombant entiers"),
            ec(2,3,4, 2,3,4, 4.0,5.0,6.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 2000, -35.0,
                listOf("limoneuse acide"), listOf("Montagnard","Sub-alpin")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                sig="Station fraîche acide montagnarde. Mauvais indicateur en plantation car très utilisé hors station."),
            hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.MONTAGNARD),
                listOf(TypeMilieu.FORET_MIXTE), listOf("Pessière","Sapinière-pessière"),
                listOf("Abieti-Piceion")),
            dist("Europe centrale et boréale","Naturel dans les Alpes et Vosges, planté partout",
                listOf("Alpes","Vosges","Massif Central (planté)")),
            phen(listOf(4,5), listOf(10,11), "200–400 ans"),
            Interactions(listOf("Abies alba","Vaccinium myrtillus"),
                mycorhizes = listOf("Suillus luteus","Lactarius deterrimus"),
                parasitesConnus = listOf("Ips typographus","Heterobasidion annosum")),
            if_(RoleForestier.ESSENCE_DOMINANTE,"Bois d'industrie très utilisé",
                listOf("Charpente","Pâte à papier","Caisses"), 4, 2,
                "Très sensible scolytes Ips typographus", listOf("Ips typographus"), 1, "Révolution 80–100 ans")),

        EspeceVegetale("TILIA_CORDATA",
            tx("Tilia cordata","Mill.","Malvaceae","Tilia","cordata","Tilleul à petites feuilles",
                listOf("Tilleul sauvage")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            morph("Cime ovoïde dense, rejet de souche abondant","20–30 m","Arbre des forêts fraîches et fertiles. Fleurs très mellifères.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "En cœur (cordiformes), 3–7 cm, asymétriques, face inférieure avec touffes de poils roux aux nervures.",
                "Cymes ombelliformes sur bractée foliacée allongée","Blanc-crème","Juin–Juillet",
                TypeFruit.AUTRE, ModeDispersion.ANEMOCHORE,"Septembre–Octobre",
                "Pivotant puis traçant, drageons abondants","Bractée allongée servant d'aile à la dissémination"),
            ec(2,3,4, 3,4,5, 5.0,6.5,8.0, true, false,
                NiveauLumiere.DEMI_OMBRE, 1500, -25.0,
                listOf("limoneuse","argilo-limoneuse"), listOf("Semi-océanique","Continental")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="Sol frais fertile et neutre. Accompagnateur du hêtre et du chêne sessile."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE),
                listOf(TypeMilieu.LISIERE), listOf("Chênaie-tillaie","Hêtraie-tillaie")),
            dist("Europe tempérée","Commun sauf extrêmes nord et méditerranéen",
                listOf("Massif Central","Bourgogne","Lorraine","Alsace")),
            phen(listOf(6,7), listOf(9,10), "300–600 ans"),
            Interactions(planteMellifere = true, planteRessourcesFaune = true),
            if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Bois léger — tournage, tisane",
                listOf("Tournage","Lutherie"), 3, 3)),

        // ── ESPÈCES INDICATRICES HERBACÉES ────────────────────────────────────

        EspeceVegetale("DESCHAMPSIA_FLEXUOSA",
            tx("Deschampsia flexuosa","(L.) Trin.","Poaceae","Deschampsia","flexuosa","Canche flexueuse",
                listOf("Canche des rochers"), listOf("Avenella flexuosa")),
            cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            morph("Graminée en touffe lâche, tiges flexueuses","30–80 cm","Petite graminée acidiphile des sous-bois et landes.",
                TypeFeuille.AIGUILLE, DispositionFeuille.ALTERNEE,
                "Très étroites (<1 mm), enroulées, rigides, vert foncé.",
                "Panicule très lâche et élégante","Argenté-violacé scintillant","Juin–Août",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Juillet–Septembre",
                "Fibreux superficiel","Inflorescence lâche aux épillets brillants"),
            ec(1,2,3, 1,1,2, 3.5,4.5,5.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 2200, -35.0,
                listOf("sableuse","graveleuse"), listOf("Continental","Semi-océanique")),
            vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE_STRICT,
                sig="INDICATEUR FORT d'acidité (pH < 5) et pauvreté. Abondance = sol sableux acide lessivé, humus de type Mor."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_RESINEUSE, TypeMilieu.LANDE),
                listOf(TypeMilieu.MONTAGNARD), listOf("Chênaie sessile acidiphile","Boulaie"),
                listOf("Quercion robori-petraeae")),
            dist("Eurasie tempérée","Très commun sur sols siliceux"),
            phen(listOf(6,7,8), listOf(7,8,9)),
            Interactions(listOf("Calluna vulgaris","Vaccinium myrtillus","Pteridium aquilinum")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("OXALIS_ACETOSELLA",
            tx("Oxalis acetosella","L.","Oxalidaceae","Oxalis","acetosella","Oxalide petite-oseille",
                listOf("Pain de coucou","Trèfle acide","Alléluia")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            morph("Petite herbacée rampante en tapis dans les sous-bois","5–15 cm","Plante rampante des sous-bois frais acides.",
                TypeFeuille.COMPOSEE_PALMATISEE, DispositionFeuille.EN_ROSETTE,
                "Trifoliées, folioles en cœur obcordées, vert clair. Se referment la nuit.",
                "Fleurs solitaires sur longs pédoncules","Blanches veinées de violet","Avril–Juin",
                TypeFruit.CAPSULE, ModeDispersion.AUTOCHORE,"Juin–Août",
                "Rhizome horizontal rampant","Feuilles à goût acide (acide oxalique). Mouvement nyctinastique."),
            ec(2,3,4, 1,2,3, 3.5,4.5,6.0, false, false,
                NiveauLumiere.PLEIN_OMBRE, 2000, -30.0),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                sig="Indicateur de sol acide frais ombragé. Tapis dense = acidité et fraîcheur confirmées. Hêtraies, sapinières."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_RESINEUSE, TypeMilieu.FORET_MIXTE),
                listOf(TypeMilieu.MONTAGNARD), listOf("Hêtraie-sapinière","Hêtraie acidiphile"),
                listOf("Luzulo-Fagion","Abieti-Piceion")),
            dist("Eurasie tempérée boréale","Commun dans les massifs montagneux, Bretagne, Normandie"),
            phen(listOf(4,5,6), vie = "Vivace pérenne"),
            Interactions(listOf("Fagus sylvatica","Abies alba")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("MERCURIALIS_PERENNIS",
            tx("Mercurialis perennis","L.","Euphorbiaceae","Mercurialis","perennis","Mercuriale vivace",
                listOf("Mercuriale des forêts")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            morph("Herbacée dressée en tapis denses","15–40 cm","Plante rhizomateuse des chênaies-charmaies fertiles. Dioïque, toxique.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Ovales-lancéolées, dentées, vert foncé mat, pubescentes.",
                "Épis axillaires dressés (mâles), femelles groupées","Verdâtre","Mars–Mai",
                TypeFruit.CAPSULE, ModeDispersion.ZOOCHORE,"Mai–Juillet",
                "Rhizome très développé colonisation clonale","Dioïque, plante toxique"),
            ec(2,3,4, 3,4,5, 5.5,6.5,8.0, true, false,
                NiveauLumiere.PLEIN_OMBRE, 1400, -20.0),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="INDICATEUR FORT de sol riche (eutrophe) et neutre à basique. Tapis = sol fertile. Chênaie-charmaie typique."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                listOf("Chênaie-charmaie à mercuriale"), listOf("Carpinion betuli")),
            dist("Europe tempérée","Commun dans les forêts de plaine fertile"),
            phen(listOf(3,4,5), vie = "Vivace clonale"),
            Interactions(listOf("Carpinus betulus","Primula elatior")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("URTICA_DIOICA",
            tx("Urtica dioica","L.","Urticaceae","Urtica","dioica","Grande ortie",
                listOf("Ortie dioïque","Ortie commune")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            morph("Herbacée dressée urticante en peuplements denses","50–150 cm","Plante nitrophile indicatrice de perturbation.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Ovales-lancéolées, grossièrement dentées, poils urticants.",
                "Grappes pendantes axillaires","Verdâtre","Juin–Septembre",
                TypeFruit.AKENE, ModeDispersion.BAROCHORE,"Juillet–Octobre",
                "Rhizome traçant jaune-orangé","Poils urticants injectant acide formique. Tige quadrangulaire."),
            ec(2,3,4, 4,5,5, 5.0,7.0,8.0, true, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1800, -20.0),
            vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.NITROPHILE, IndicAcidite.NEUTROPHILE,
                perturb=true, fert=true,
                sig="INDICATEUR FORT de sol nitrophile et perturbé. Signal d'apport excessif d'azote ou de dérangement anthropique."),
            hab(listOf(TypeMilieu.LISIERE, TypeMilieu.MILIEU_PERTURBE, TypeMilieu.RIPISYLVE),
                listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.TALUS_HAIES)),
            dist("Cosmopolite tempéré","Ubiquiste — partout"),
            phen(listOf(6,7,8,9), vie = "Vivace"),
            Interactions(planteRessourcesFaune = true),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("MOLINIA_CAERULEA",
            tx("Molinia caerulea","(L.) Moench","Poaceae","Molinia","caerulea","Molinie bleue",
                listOf("Molinie commune")),
            cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            morph("Grandes touffes denses, tiges dressées","40–150 cm","Graminée des zones humides acides et tourbières.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Plates et larges (4–8 mm), allongées, base étranglée. Reflets bleutés-violacés.",
                "Panicule contractée violacée","Violet-bleu","Juillet–Septembre",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Septembre–Novembre",
                "Fibreux adapté sols hydromorphes","Un seul nœud sur la tige (caractère distinctif)"),
            ec(3,4,5, 1,2,3, 3.5,4.5,6.5, false, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 2000, -30.0,
                listOf("tourbeuse","argileuse acide")),
            vi(IndicHumidite.HYGROPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                hydro=true, sig="INDICATEUR D'HYDROMORPHIE sur sol acide. Engorgement périodique ou nappe peu profonde."),
            hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.LANDE, TypeMilieu.TOURBIERE),
                listOf(TypeMilieu.FORET_FEUILLUE), listOf("Moliniaie","Lande humide")),
            dist("Europe et Asie occidentale","Très commun sur sols acides et humides",
                listOf("Bretagne","Landes","Massif Central")),
            phen(listOf(7,8,9), listOf(9,10,11)),
            Interactions(listOf("Calluna vulgaris","Erica tetralix")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("FILIPENDULA_ULMARIA",
            tx("Filipendula ulmaria","(L.) Maxim.","Rosaceae","Filipendula","ulmaria","Reine des prés",
                listOf("Spirée ulmaire","Herbe aux abeilles")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            morph("Herbacée dressée à grandes feuilles et tiges anguleuses","60–150 cm","Plante des bords de rivière et zones humides. Fleurs en corymbe blanc parfumé.",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "Imparipennées, folioles intermédiaires petites, terminale grande lobée 3-5. Blanche dessous.",
                "Corymbes denses","Blanc crème très parfumé","Juin–Août",
                TypeFruit.AKENE, ModeDispersion.HYDROCHORE,"Juillet–Septembre",
                "Rhizome traçant adapté sols engorgés","Fleurs odeur miel caractéristique"),
            ec(4,5,5, 3,4,5, 5.0,6.5,7.5, true, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 1600, -25.0),
            vi(IndicHumidite.HYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro=true, sig="INDICATEUR de bord de cours d'eau, prairie humide fertile, sol gorgé d'eau en hiver."),
            hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.ZONE_HUMIDE, TypeMilieu.PRAIRIE_FORESTIERE)),
            dist("Eurasie tempérée","Commun sur tout le territoire"),
            phen(listOf(6,7,8), listOf(7,8,9)),
            Interactions(listOf("Alnus glutinosa","Fraxinus excelsior"), planteMellifere = true),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("JUNCUS_EFFUSUS",
            tx("Juncus effusus","L.","Juncaceae","Juncus","effusus","Jonc épars",
                listOf("Jonc diffus")),
            cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            morph("Touffes de tiges cylindriques vert brillant, rigides","40–120 cm","Jonc pionnier des zones marécageuses et dépressions.",
                TypeFeuille.AUTRE, DispositionFeuille.ALTERNEE,
                "Tiges cylindriques remplies d'une moelle blanche, feuilles réduites à des gaines basales.",
                "Glomérules lâches à mi-hauteur de la tige","Brun-verdâtre","Juin–Août",
                TypeFruit.CAPSULE, ModeDispersion.HYDROCHORE,"Juillet–Septembre",
                "Fibreux, rhizome court","Feuilles réduites. Inflorescence paraît latérale."),
            ec(4,5,5, 1,2,4, 4.0,5.5,7.0, false, true,
                NiveauLumiere.PLEIN_SOLEIL, 1800, -30.0),
            vi(IndicHumidite.HYGROPHYTE_STRICT, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                hydro=true, compac=true,
                sig="INDICATEUR FORT d'hydromorphie permanente et de compaction du sol. Présence = sol engorgé et/ou tassé."),
            hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.PRAIRIE_FORESTIERE, TypeMilieu.RIPISYLVE),
                listOf(TypeMilieu.MILIEU_PERTURBE)),
            dist("Cosmopolite tempéré","Commun partout sur sols engorgés"),
            phen(listOf(6,7,8), listOf(7,8,9)),
            Interactions(listOf("Molinia caerulea","Carex spp.")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("CALLUNA_VULGARIS",
            tx("Calluna vulgaris","(L.) Hull","Ericaceae","Calluna","vulgaris","Callune",
                listOf("Bruyère commune","Fausse bruyère")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.SOUS_ARBUSTE),
            morph("Sous-arbuste à tiges ligneuses dressées ou couchées","20–60 cm","Sous-arbuste dominant des landes acidiphiles.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Très petites, imbriquées, semblables à des écailles, persistantes.",
                "Grappes unillatérales de fleurs en clochettes","Rose-lilas","Juillet–Octobre",
                TypeFruit.CAPSULE, ModeDispersion.ANEMOCHORE,"Octobre–Novembre",
                "Fibreux mycotrophique","Fleurs à 4 sépales pétaloïdes plus grands que les pétales"),
            ec(1,2,3, 1,1,2, 3.5,4.5,5.5, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 2500, -35.0,
                listOf("sableuse acide","tourbeuse")),
            vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE_STRICT,
                sig="INDICATEUR FORT d'acidité et de pauvreté. Landes, dunes intérieures, forêts claires sur sable acide."),
            hab(listOf(TypeMilieu.LANDE, TypeMilieu.FORET_RESINEUSE),
                listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.MONTAGNARD),
                listOf("Lande à callune","Calluno-Ulicetum")),
            dist("Europe atlantique et continentale","Très commun sur sols siliceux",
                listOf("Bretagne","Landes","Massif Central","Vosges","Ardennes")),
            phen(listOf(7,8,9,10), listOf(10,11)),
            Interactions(listOf("Deschampsia flexuosa","Pinus sylvestris"), planteMellifere = true),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("ANEMONE_NEMOROSA",
            tx("Anemone nemorosa","L.","Ranunculaceae","Anemone","nemorosa","Anémone sylvie",
                listOf("Anémone des bois")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            morph("Petite herbacée éphémère printanière","10–30 cm","Géophyte printanier formant des tapis en forêts fraîches.",
                TypeFeuille.COMPOSEE_PALMATISEE, DispositionFeuille.VERTICILLEE,
                "3 feuilles verticillées à mi-tige, profondément palmatilobées.",
                "Fleur solitaire terminale","Blanc (parfois rosé)","Mars–Mai",
                TypeFruit.AKENE, ModeDispersion.MYRMECOCHORE,"Mai–Juin",
                "Rhizome horizontal rampant","Géophyte éphémère printanier. Plante toxique."),
            ec(2,3,3, 2,3,4, 5.0,6.5,7.5, true, false,
                NiveauLumiere.DEMI_OMBRE, 1600, -25.0),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de forêt ancienne (bonne continuité forestière). Sol frais et profond."),
            hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                listOf("Chênaie-charmaie","Hêtraie fraîche"), listOf("Carpinion betuli")),
            dist("Europe tempérée","Commun dans les forêts de plaine"),
            phen(listOf(3,4,5), listOf(5,6)),
            Interactions(listOf("Carpinus betulus","Primula elatior")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("PTERIDIUM_AQUILINUM",
            tx("Pteridium aquilinum","(L.) Kuhn","Dennstaedtiaceae","Pteridium","aquilinum","Fougère aigle",
                listOf("Grande fougère")),
            cl(GroupeBiologique.FOUGERE, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            morph("Grandes frondes tripennées horizontales sur tiges dressées","50–200 cm","Plus grande fougère européenne. Colonise les sous-bois acides clairs.",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.ALTERNEE,
                "Frondes tripennées, pennules lancéolées, sores linéaires sur les bords recourbés.",
                "Pas de fleurs (sporophyte)","—","—",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Juillet–Septembre",
                "Rhizome profond jusqu'à 1 m, très étendu","Frondes en crosse en début de saison. Très résistant au feu."),
            ec(1,2,4, 1,2,3, 3.5,5.0,6.5, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 1800, -30.0,
                listOf("sableuse","graveleuse"), listOf("Continental","Semi-océanique","Atlantique")),
            vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                perturb=true, sig="Indicateur de sol acide et milieu ouvert ou perturbé (coupe, incendie). Rhizome profond résistant au feu."),
            hab(listOf(TypeMilieu.LANDE, TypeMilieu.LISIERE, TypeMilieu.FORET_FEUILLUE),
                listOf(TypeMilieu.MILIEU_PERTURBE, TypeMilieu.CLAIRIERE)),
            dist("Cosmopolite tempéré","Très commun, toute la France"),
            phen(listOf(5,6,7), listOf(7,8)),
            Interactions(listOf("Calluna vulgaris","Quercus petraea","Betula pendula")),
            if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("VACCINIUM_MYRTILLUS",
            tx("Vaccinium myrtillus","L.","Ericaceae","Vaccinium","myrtillus","Myrtille commune",
                listOf("Airelle myrtille","Bleuet")),
            cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.SOUS_ARBUSTE),
            morph("Sous-arbuste à tiges vertes anguleuses, feuilles caduques","10–50 cm","Sous-arbuste des forêts acides montagnardes. Baies comestibles bleues.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Ovales, finement dentées, caduques, vert vif. Tiges vertes anguleuses distinctives.",
                "Fleurs solitaires axillaires en urne","Rose-verdâtre","Avril–Juin",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Juillet–Août",
                "Fibreux mycotrophique, traçant","Baies bleues-noires comestibles, riches en anthocyanes"),
            ec(2,3,4, 1,2,3, 3.5,4.5,5.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 2500, -40.0,
                listOf("sablo-limoneuse acide","tourbeuse"), listOf("Montagnard","Sub-alpin")),
            vi(IndicHumidite.MESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE_STRICT,
                sig="INDICATEUR de forêt acide montagnarde. Sol acide pauvre, bien drainé à légèrement humide."),
            hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.FORET_FEUILLUE, TypeMilieu.LANDE),
                listOf(TypeMilieu.MONTAGNARD), listOf("Hêtraie acidiphile","Pessière à myrtilles"),
                listOf("Luzulo-Fagion","Abieti-Piceion")),
            dist("Eurasie boréale et montagneuse","Commun dans les massifs, moins fréquent en plaine",
                listOf("Vosges","Alpes","Pyrénées","Massif Central","Ardennes")),
            phen(listOf(4,5,6), listOf(7,8)),
            Interactions(listOf("Picea abies","Abies alba"), mycorhizes = listOf("Ericoid mycorrhizas"),
                planteRessourcesFaune = true),
            if_(RoleForestier.INDICATRICE))
    )
}
