package com.forestry.counter.domain.usecase.florist

// ═══════════════════════════════════════════════════════════════════════════════
//  FloristDatabaseExtension.kt — 30 espèces indicatrices complémentaires
//
//  Priorité : espèces à haute valeur diagnostique (ripisylve, acido-basité,
//  hydromorphie, perturbation, milieux montagnards, méditerranéens).
//  Sources : Flora Gallica, Indicateurs phytosociologiques de Rameau et al.,
//  Valeurs d'Ellenberg françaises, INPN.
// ═══════════════════════════════════════════════════════════════════════════════

internal object FloristDatabaseExtension {

    // Alias sur les helpers de FloristDatabase (internal)
    private val D = FloristDatabase

    val SPECIES: List<EspeceVegetale> = listOf(

        // ── ARBRES COMPLÉMENTAIRES ─────────────────────────────────────────────

        EspeceVegetale("QUERCUS_PUBESCENS",
            D.tx("Quercus pubescens","Willd.","Fagaceae","Quercus","pubescens","Chêne pubescent",
                listOf("Chêne blanc","Chêne durmast")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Cime irrégulière, port souvent tortueux","10–20 m","Chêne thermophile des versants chauds calcaires. Feuilles et jeunes rameaux pubescents.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Lobées, base arrondie ou légèrement cordée, pubescentes des 2 côtés, pétiole 1–2 cm.",
                "Chatons mâles pendants","Verdâtre","Avril–Mai",
                TypeFruit.GLAND, ModeDispersion.ZOOCHORE,"Octobre–Novembre",
                "Pivotant profond — adapté aux sols calcaires secs","Cupule hémisphérique à écailles couchées pubescentes"),
            D.ec(1,2,3, 1,2,4, 6.0,7.5,8.5, true, false,
                NiveauLumiere.PLEIN_SOLEIL, 1200, -20.0,
                listOf("calcaire","argilo-calcaire"), listOf("Méditerranéen","Supra-méditerranéen")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.BASOPHILE,
                sig="Indicateur de sol sec calcaire. Versants chauds sud et sud-ouest, calcaires, collines méridionales."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.LISIERE), listOf(TypeMilieu.MILIEU_ROCHEUX),
                listOf("Chênaie pubescente","Chênaie verte"), listOf("Quercion pubescenti-petraeae")),
            D.dist("Méditerranée et Europe méridionale","Commun dans le Midi et les collines calcaires",
                listOf("Occitanie","PACA","Auvergne-Rhône-Alpes","Nouvelle-Aquitaine (versants calcaires)")),
            D.phen(listOf(4,5), listOf(10,11), "200–500 ans"),
            Interactions(listOf("Buxus sempervirens","Cistus spp."), mycorhizes = listOf("Tuber melanosporum (potentiel)")),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Faible — bois dur tortueux",
                listOf("Chauffage"), 1, 2, "Résistant sécheresse", emptyList(), 4)),

        EspeceVegetale("PSEUDOTSUGA_MENZIESII",
            D.tx("Pseudotsuga menziesii","(Mirb.) Franco","Pinaceae","Pseudotsuga","menziesii","Douglas de Menzies",
                listOf("Douglas vert","Sapin de Douglas","Douglasie"),
                listOf("Pseudotsuga douglasii","Abies douglasii")),
            D.cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE,
                StatutIndigene.INTRODUITE),
            D.morph("Grand arbre élancé, fût droit cylindrique","40–60 m","Conifère nordaméricain à très fort potentiel ligneux. Aiguilles aromatiques à anneaux sur les rameaux.",
                TypeFeuille.AIGUILLE, DispositionFeuille.ALTERNEE,
                "Aiguilles plates 2–3 cm, sillonnées dessus, 2 bandes blanches dessous, odeur d'agrumes.",
                "Cônes mâles rougeâtres, femelles pendants","—","Mars–Avril",
                TypeFruit.CONE, ModeDispersion.ANEMOCHORE,"Automne",
                "Pivotant très profond — résistant à la sécheresse","Cône à bractées tridentées très caractéristique"),
            D.ec(2,3,4, 2,3,4, 4.0,5.5,7.0, false, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1800, -25.0,
                listOf("limoneuse","sablo-limoneuse"), listOf("Océanique","Sub-montagnard")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Plantation productive. Sol profond bien drainé, frais à modérément sec. Polyvalent."),
            D.hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.FORET_MIXTE), emptyList(),
                listOf("Pessière-sapinière à Douglas"), listOf("plantations")),
            D.dist("Côte pacifique d'Amérique du Nord","Très répandu en plantation sur tout le territoire",
                listOf("Massif Central","Bretagne","Normandie","Grand Est","Auvergne-Rhône-Alpes")),
            D.phen(listOf(3,4), listOf(9,10), "500–1000 ans (en nat.)"),
            Interactions(listOf("Abies alba","Picea abies"), mycorhizes = listOf("Laccaria bicolor","Rhizopogon spp.")),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Très élevée — bois d'œuvre polyvalent",
                listOf("Charpente","Parquet","Menuiserie","Contreplaqué"), 2, 3,
                "Sensible Heterobasidion annosum, armillaire", listOf("Heterobasidion annosum"), 3, "Révolution 50–80 ans")),

        EspeceVegetale("LARIX_DECIDUA",
            D.tx("Larix decidua","Mill.","Pinaceae","Larix","decidua","Mélèze d'Europe",
                listOf("Mélèze commun","Mélèze des Alpes")),
            D.cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Grand arbre caduc, cime pyramidale, rameaux retombants","25–45 m","Seul conifère caduc d'Europe. Lumière et froid extrême. Bois durable.",
                TypeFeuille.AIGUILLE, DispositionFeuille.EN_ROSETTE,
                "Aiguilles caduques souples 2–3 cm, en rosettes de 20–40, vert clair au printemps, jaunissant en automne.",
                "Chatons mâles jaunes, femelles roses","Rosé (femelles)","Mars–Avril",
                TypeFruit.CONE, ModeDispersion.ANEMOCHORE,"Automne",
                "Pivotant profond, résistant au vent","Cônes ovales 2–4 cm, bractées non saillantes"),
            D.ec(2,3,4, 1,2,3, 5.0,6.5,7.5, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 2500, -40.0,
                listOf("calcaire","morainique"), listOf("Alpin","Sub-alpin","Montagnard")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur de milieu alpin/subalpin. Sol minéral peu évolué, froid extrême, fort ensoleillement."),
            D.hab(listOf(TypeMilieu.MONTAGNARD, TypeMilieu.FORET_RESINEUSE), emptyList(),
                listOf("Mélèzin alpin","Mélézin subalpin"), listOf("Rhododendro-Laricion")),
            D.dist("Alpes et Carpates","Commun dans les Alpes françaises, reboisements",
                listOf("Alpes","Pyrénées (introductions)","Massif Central (reboisements)")),
            D.phen(listOf(3,4), listOf(10,11), "500–800 ans"),
            Interactions(listOf("Pinus cembra","Rhododendron ferrugineum"),
                mycorhizes = listOf("Suillus grevillei","Suillus viscidus")),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Élevée — bois très durable",
                listOf("Charpente extérieure","Bardage","Revêtement"), 1, 1,
                "Résistant", emptyList(), 4, "Révolution 80–120 ans")),

        EspeceVegetale("PINUS_PINASTER",
            D.tx("Pinus pinaster","Aiton","Pinaceae","Pinus","pinaster","Pin maritime",
                listOf("Pin mésogéen","Pin des Landes"),
                listOf("Pinus maritima")),
            D.cl(GroupeBiologique.GYMNOSPERME, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Fût droit ou courbé à la base, cime étalée","20–35 m","Pin de la forêt landaise (1er massif forestier de plaine d'Europe de l'Ouest).",
                TypeFeuille.AIGUILLE, DispositionFeuille.OPPOSEE,
                "Longues aiguilles 15–22 cm, par 2, rigides, vert glauque. Gaines persistantes 12–18 mm.",
                "Cônes mâles jaunes, femelles","—","Avril–Mai",
                TypeFruit.CONE, ModeDispersion.ANEMOCHORE,"Automne année 2",
                "Pivotant puissant adapté sables","Gros cônes 10–20 cm, persistants plusieurs années sur l'arbre"),
            D.ec(1,2,3, 1,1,2, 4.0,5.0,6.0, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 800, -15.0,
                listOf("sableuse","sablo-graveleuse"), listOf("Atlantique","Méditerranéen")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                sig="Sol sableux acide pauvre drainé. Landes atlantiques et méditerranéennes. Économiquement crucial Landes de Gascogne."),
            D.hab(listOf(TypeMilieu.FORET_RESINEUSE, TypeMilieu.LANDE), emptyList(),
                listOf("Pinède maritime","Pineraie landaise"), listOf("Molinio-Pinion")),
            D.dist("Circum-méditerranéen et atlantique","Très commun Landes, Côtes atlantiques, Var",
                listOf("Landes","Gironde","Charentes","Pyrénées-Atlantiques","Var")),
            D.phen(listOf(4,5), listOf(9,10,11), "150–300 ans"),
            Interactions(listOf("Molinia caerulea","Calluna vulgaris"),
                mycorhizes = listOf("Rhizopogon roseolus","Suillus collinitus")),
            D.if_(RoleForestier.ESSENCE_DOMINANTE,"Élevée — papier, construction",
                listOf("Pâte à papier","Résine","Pieux","Palettes"), 2, 4,
                "Sensible tempêtes, scolytes, incendie", listOf("Dioryctria sylvestrella"), 2, "Révolution 35–50 ans")),

        EspeceVegetale("PRUNUS_AVIUM",
            D.tx("Prunus avium","(L.) L.","Rosaceae","Prunus","avium","Merisier",
                listOf("Cerisier sauvage","Cerisier des oiseaux")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Arbre élancé, fût droit, écorce brillante brun-rouge","15–25 m","Bois précieux à grain fin. Fleurs blanches spectaculaires. Indicateur de sol riche.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Ovales-elliptiques, dentées, 2 glandes à la base du limbe ou sur le pétiole, vert terne.",
                "Corymbes de fleurs blanches","Blanc","Avril (avant feuilles)",
                TypeFruit.DRUPE, ModeDispersion.ZOOCHORE,"Juin–Juillet",
                "Pivotant peu profond, drageonnant","Écorce à lenticelles horizontales caractéristique"),
            D.ec(2,3,4, 3,4,5, 5.5,6.5,7.5, false, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1500, -25.0,
                listOf("limoneuse","limon-argileuse"), listOf("Semi-océanique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur de sol fertile, profond, bien drainé, neutre à légèrement acide. Sol favorable à la sylviculture."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                listOf("Chênaie-charmaie","Hêtraie-chênaie"), listOf("Carpinion betuli","Fagion")),
            D.dist("Europe, Asie occidentale","Commun partout sauf extrême Nord et Méditerranée aride"),
            D.phen(listOf(4), listOf(6,7), "80–150 ans"),
            Interactions(listOf("Quercus robur","Fraxinus excelsior"), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Très élevée — ébénisterie, lutherie",
                listOf("Ébénisterie","Lutherie","Sculpture","Tournage"), 3, 3,
                "Sensible armillaire, bactéries de chancre", listOf("Pseudomonas syringae"), 3, "Révolution 60–80 ans")),

        EspeceVegetale("POPULUS_TREMULA",
            D.tx("Populus tremula","L.","Salicaceae","Populus","tremula","Tremble",
                listOf("Tremble commun","Peuplier tremble")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Arbre élancé, cime claire, feuilles frémissantes","15–25 m","Arbre pionnier et de lumière. Feuilles en perpétuel mouvement.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Arrondies, sinuées-dentées, long pétiole aplati latéralement (tremblement caractéristique).",
                "Chatons pendants","Rouge (mâle), vert (femelle)","Février–Mars",
                TypeFruit.CAPSULE, ModeDispersion.ANEMOCHORE,"Avril–Mai",
                "Drageonnant intense (rejets racinaires)","Premier colonisateur des coupes, tremble au vent"),
            D.ec(2,3,4, 2,3,4, 4.0,5.5,7.0, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 2000, -35.0),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                perturb=true, sig="Espèce pionnière après coupe ou incendie. Drageonne abondamment. Indique ouverture récente."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.CLAIRIERE, TypeMilieu.LISIERE), emptyList(),
                listOf("Tremblaie"), listOf("Betulion pendulae")),
            D.dist("Eurasie boréale","Commun partout, toute la France"),
            D.phen(listOf(2,3), listOf(4,5), "80–150 ans"),
            Interactions(listOf("Betula pendula","Salix caprea"),
                planteRessourcesFaune = true,
                mycorhizes = listOf("Pholiota aurivella","Phellinus tremulae")),
            D.if_(RoleForestier.ESSENCE_PIONNIERE,"Faible — papier, allumettes",
                listOf("Pâte à papier","Allumettes"), 4, 1, "Rouille, chancre", emptyList(), 2)),

        EspeceVegetale("ACER_CAMPESTRE",
            D.tx("Acer campestre","L.","Sapindaceae","Acer","campestre","Érable champêtre",
                listOf("Acer de haies","Érable des champs","Acérable")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Petit arbre ou arbuste, fût court, ramification dense","5–15 m","Espèce calcicole de lisière et sous-bois. Latex blanc dans les pétioles.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "5 lobes arrondis à sinus peu profonds, base cordée, pétiole avec latex blanc à la cassure.",
                "Corymbes érigés","Vert-jaunâtre","Avril–Mai",
                TypeFruit.SAMARE, ModeDispersion.ANEMOCHORE,"Août–Octobre",
                "Traçant, peu profond","Latex blanc du pétiole : caractère distinctif"),
            D.ec(2,3,4, 3,4,5, 5.5,7.0,8.5, true, false,
                NiveauLumiere.DEMI_OMBRE, 1000, -25.0,
                listOf("argilo-calcaire","limono-argileuse"), listOf("Semi-océanique","Continental")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.BASOPHILE,
                sig="Indicateur de sol calcaire neutre à basique, fertile. Lisières et haies bocagères calcaires."),
            D.hab(listOf(TypeMilieu.LISIERE, TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Chênaie-charmaie calcicole"), listOf("Carpinion betuli")),
            D.dist("Europe et Asie occidentale","Commun hors zones acides et montagnes",
                listOf("Bassin Parisien","Bourgogne","Centre","Normandie calcaire")),
            D.phen(listOf(4,5), listOf(8,9,10), "100–200 ans"),
            Interactions(listOf("Crataegus monogyna","Carpinus betulus"), planteMellifere = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Moyenne — ébénisterie fine",
                listOf("Ébénisterie","Marqueterie"), 3, 2)),

        EspeceVegetale("CORYLUS_AVELLANA",
            D.tx("Corylus avellana","L.","Betulaceae","Corylus","avellana","Noisetier commun",
                listOf("Coudrier","Noisetier sauvage","Avelinier")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste multicaule, drageons nombreux","2–6 m","Arbuste de sous-bois le plus commun de France. Fleurs mâles en chatons jaunes dès janvier.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Rondes-ovales, doublement dentées, base cordée, velues sur les 2 faces. Court pétiole glanduleux.",
                "Chatons mâles jaunes pendants","Jaune (mâle), minuscule rouge (femelle)","Janvier–Mars",
                TypeFruit.NOISETTE, ModeDispersion.ZOOCHORE,"Août–Octobre",
                "Souche drageonnante, racines étendues","Fleurs hermaphrodites mais pollinisation croisée"),
            D.ec(2,3,4, 3,4,5, 5.5,6.5,7.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1400, -25.0),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.NEUTROPHILE,
                sig="Indique sol de bonne fertilité, pas trop acide ni trop sec. Très commun en sous-bois."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.LISIERE), emptyList(),
                listOf("Chênaie-charmaie"), listOf("Carpinion","Alno-Ulmion")),
            D.dist("Europe et Asie occidentale","Très commun partout sauf méditerranéen aride"),
            D.phen(listOf(1,2,3), listOf(8,9,10)),
            Interactions(listOf("Carpinus betulus","Quercus robur"), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible — cannes, clayonnage",
                listOf("Cannes","Clôtures","Charbon"), 3, 2)),

        EspeceVegetale("SAMBUCUS_NIGRA",
            D.tx("Sambucus nigra","L.","Adoxaceae","Sambucus","nigra","Sureau noir",
                listOf("Sambeau","Sureau commun")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste ou petit arbre à moelle blanche","3–8 m","Nitrophile marqué. Tige à moelle blanche. Odeur désagréable des feuilles froissées.",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.OPPOSEE,
                "Imparipennées, 5–7 folioles ovales dentées, odeur forte au froissement.",
                "Corymbes plats denses","Blanc crème","Mai–Juillet",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Août–Octobre",
                "Fibreux, traçant","Tige creuse avec moelle blanche — caractère distinctif"),
            D.ec(3,4,5, 4,5,6, 5.5,7.0,7.5, false, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 1000, -25.0),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.NITROPHILE, IndicAcidite.NEUTROPHILE,
                perturb=true, fert=true,
                sig="FORT INDICATEUR de nitrophilie et perturbation. Sol riche en azote (déjections animales, déchets organiques, coupes). Lisiière perturbée."),
            D.hab(listOf(TypeMilieu.LISIERE, TypeMilieu.MILIEU_PERTURBE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Sambucetalia"), listOf("Sambuco-Salicion")),
            D.dist("Europe et Asie","Très commun, indicateur de perturbation nitrophile"),
            D.phen(listOf(5,6,7), listOf(8,9,10)),
            Interactions(planteRessourcesFaune = true, planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("ILEX_AQUIFOLIUM",
            D.tx("Ilex aquifolium","L.","Aquifoliaceae","Ilex","aquifolium","Houx commun",
                listOf("Houx","Agrifolier","Bois-fleuri")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBUSTE),
            D.morph("Arbuste à arbre persistant, cime conique dense","2–15 m","Seul arbuste indigène toujours vert de nos forêts. Très ombrophile.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Coriaces persistantes, ondulées-épineuses (jeunes) ou ovales-entières (adultes), vert luisant.",
                "Petites fleurs en fascicules axillaires","Blanc","Mai–Juin",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Octobre–Février",
                "Traçant, touffes profondes","Dimorphisme foliaire selon âge"),
            D.ec(2,3,4, 2,3,4, 4.0,5.5,7.0, false, false,
                NiveauLumiere.DEMI_OMBRE, 1000, -15.0,
                listOf("limoneuse acide"), listOf("Atlantique","Océanique")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Indicateur d'influence atlantique (hiver doux). Sol acide à neutre, bien drainé. Sous-bois de hêtraies et chênaies oceaniques."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.FORET_MIXTE, TypeMilieu.LISIERE),
                listOf("Hêtraie atlantique à houx","Chênaie sessile atlantique"), listOf("Ilici-Fagion")),
            D.dist("Europe atlantique et méditérranéenne","Commun Bretagne, Normandie, SW France, Pyrénées",
                listOf("Bretagne","Normandie","Pyrénées","Pays basque","Basques")),
            D.phen(listOf(5,6), listOf(10,11,12), "300–500 ans"),
            Interactions(planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Faible — taille décorative",
                listOf("Décoration"), 4, 4, "Sensible gel tardif", emptyList(), 3)),

        EspeceVegetale("SORBUS_TORMINALIS",
            D.tx("Sorbus torminalis","(L.) Crantz","Rosaceae","Sorbus","torminalis","Alisier torminal",
                listOf("Alisier blanc","Alouchier")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.ARBRE),
            D.morph("Petit arbre à cime arrondie irrégulière","8–20 m","Bois précieux parmi les plus rares. Indicateur de chênaie calcaire ancienne.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Lobées (3–4 paires), ressemblant à une étoile, base cordée, vert lustré dessus.",
                "Corymbes denses","Blanc","Avril–Mai",
                TypeFruit.POMELLE, ModeDispersion.ZOOCHORE,"Août–Octobre",
                "Pivotant profond","Fruits bruns tachetés de lenticelles, comestibles (alises)"),
            D.ec(2,3,4, 2,3,5, 6.0,7.0,8.0, true, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1200, -25.0,
                listOf("calcaire","argilo-calcaire")),
            D.vi(IndicHumidite.XEROMESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.BASOPHILE,
                sig="Indicateur de sol calcaire bien drainé, chênaie-charmaie ancienne de qualité. Bois précieux exceptionnel."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE, TypeMilieu.MILIEU_ROCHEUX),
                listOf("Chênaie-charmaie calcicole"), listOf("Carpinion betuli","Quercion pubescenti-petraeae")),
            D.dist("Europe occidentale et centrale","Dispersé, jamais dominant",
                listOf("Bourgogne","Centre","Normandie calcaire","Grand Est")),
            D.phen(listOf(4,5), listOf(8,9,10), "150–200 ans"),
            Interactions(listOf("Quercus petraea","Carpinus betulus"), planteRessourcesFaune = true),
            D.if_(RoleForestier.ESSENCE_ACCOMPAGNATRICE,"Très élevée — ébénisterie ultra-fine",
                listOf("Ébénisterie d'art","Lutherie","Objets de luxe"), 2, 2)),

        // ── HERBACÉES INDICATRICES SOL FRAIS / RICHE ──────────────────────────

        EspeceVegetale("GALIUM_ODORATUM",
            D.tx("Galium odoratum","(L.) Scop.","Rubiaceae","Galium","odoratum","Aspérule odorante",
                listOf("Woodruff","Aspérule","Belle-étoile"),
                listOf("Asperula odorata")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Herbacée stolonifère formant des tapis denses","10–30 cm","Tapis blanc caractéristique en hêtraies-chênaies fraîches et fertiles. Odeur de foin sec (coumarine).",
                TypeFeuille.SIMPLE, DispositionFeuille.VERTICILLEE,
                "Verticilles de 6–8 feuilles lancéolées, rebord scabre, odeur de foin sec au séchage.",
                "Petites fleurs en cymes","Blanc","Avril–Juin",
                TypeFruit.AKENE, ModeDispersion.ZOOCHORE,"Juin–Juillet",
                "Rhizome traçant à nœuds caractéristiques","Odeur de coumarine au froissement ou séchage"),
            D.ec(2,3,4, 3,4,5, 5.5,6.5,7.5, true, false,
                NiveauLumiere.DEMI_OMBRE, 1600, -25.0,
                listOf("limoneuse","limon-argileuse")),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                sig="INDICATEUR FIABLE de hêtraie-chênaie fraîche et fertile, sol neutre profond. Forêt ancienne stable."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE), emptyList(),
                listOf("Hêtraie neutrophile","Chênaie-charmaie"), listOf("Carpinion betuli","Fagion sylvaticae")),
            D.dist("Eurasie tempérée","Commun sauf zones méridionales et atlantiques extrêmes"),
            D.phen(listOf(4,5,6), listOf(6,7)),
            Interactions(listOf("Fagus sylvatica","Mercurialis perennis","Carex sylvatica")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("MILIUM_EFFUSUM",
            D.tx("Milium effusum","L.","Poaceae","Milium","effusum","Millet diffus",
                listOf("Millet des forêts","Millet épars")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Graminée à tiges fines gracieuses, panicule étalée","60–120 cm","Graminée gracieuse des sous-bois fertiles et frais. Panicule très diffuse.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Plates, larges (8–15 mm), tendres, molles, vert pâle luisant.",
                "Panicule très lâche, rameaux très fins retombants","Verdâtre","Mai–Juillet",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Juillet–Août",
                "Fibreux, touffes","Épillets uniflores brillants, panicule très ouverte"),
            D.ec(2,3,4, 3,4,5, 5.0,6.5,7.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1600, -25.0,
                listOf("limoneuse","limon-argileuse")),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de sol frais-humide fertile bien aéré. Hêtraies-chênaies fraîches neutrophiles."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE), emptyList(),
                listOf("Hêtraie fraîche","Chênaie-charmaie fertile"), listOf("Fagion")),
            D.dist("Eurasie boréale et tempérée","Assez commun, forêts fraîches",
                listOf("Vosges","Normandie","Bretagne","Alpes","Massif Central")),
            D.phen(listOf(5,6,7), listOf(7,8)),
            Interactions(listOf("Fagus sylvatica","Galium odoratum")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("CAREX_SYLVATICA",
            D.tx("Carex sylvatica","Huds.","Cyperaceae","Carex","sylvatica","Laîche des bois",
                listOf("Carex des forêts")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Touffes lâches de feuilles souples, épis retombants","30–60 cm","Laîche finement retombante. Très commune en sous-bois frais et ombragés.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Plates souples 3–6 mm, vert pâle, ligule courte.",
                "Épis mâles terminaux, 3–6 épis femelles pendants","Verdâtre","Mai–Juin",
                TypeFruit.AKENE, ModeDispersion.ZOOCHORE,"Juin–Août",
                "Fibreux, touffes","Épis femelles très retombants à maturité — distinctif"),
            D.ec(3,4,5, 3,4,5, 5.0,6.5,7.5, true, false,
                NiveauLumiere.DEMI_OMBRE, 1500, -25.0),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de sous-bois frais, sol profond et ombragé. Chênaies-charmaies et hêtraies moyennement fertiles."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE), emptyList(),
                listOf("Chênaie-charmaie","Hêtraie fraîche"), listOf("Carpinion betuli")),
            D.dist("Europe occidentale et centrale","Commun partout en sous-bois frais"),
            D.phen(listOf(5,6), listOf(6,7,8)),
            Interactions(listOf("Mercurialis perennis","Galium odoratum")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("PRIMULA_ELATIOR",
            D.tx("Primula elatior","(L.) Hill","Primulaceae","Primula","elatior","Primevère élevée",
                listOf("Coucou des bois","Primevère des bois")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Rosette de feuilles chiffonnées, scape florifère dressé","15–35 cm","Indicateur de forêt ancienne et de sol frais fertile. Fleurs jaune pâle à gorge orangée.",
                TypeFeuille.SIMPLE, DispositionFeuille.EN_ROSETTE,
                "Ovales-elliptiques ridées, bord irrégulièrement denté, base décurrente sur le pétiole ailé.",
                "Ombelle de 5–15 fleurs sur scape dressé","Jaune soufre (gorge orangée)","Mars–Mai",
                TypeFruit.CAPSULE, ModeDispersion.MYRMECOCHORE,"Mai–Juin",
                "Souche fibreuse courte","Fleur jaune pâle — à distinguer de P. veris (jaune doré)"),
            D.ec(2,3,4, 3,4,5, 5.5,6.5,7.5, true, false,
                NiveauLumiere.DEMI_OMBRE, 1600, -25.0),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur fiable de forêt ancienne, sol frais profond et fertile à neutre. Valeur patrimoniale."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE, TypeMilieu.PRAIRIE_FORESTIERE),
                listOf("Chênaie-charmaie fraîche"), listOf("Carpinion betuli")),
            D.dist("Europe tempérée","Commun centre et nord France, rare Méditerranée"),
            D.phen(listOf(3,4,5), listOf(5,6)),
            Interactions(listOf("Anemone nemorosa","Mercurialis perennis")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("VIOLA_REICHENBACHIANA",
            D.tx("Viola reichenbachiana","Jord. ex Boreau","Violaceae","Viola","reichenbachiana","Violette des forêts",
                listOf("Violette sylvestre","Violette de Reichenbach"),
                listOf("Viola sylvestris")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Petite herbacée à rhizome, feuilles cordées","5–15 cm","Violette des sous-bois ombragés. Pétale inférieur strié de violet foncé.",
                TypeFeuille.SIMPLE, DispositionFeuille.EN_ROSETTE,
                "Cordées-ovales, bord crénelé, stipules étroites laciniées.",
                "Fleurs solitaires sur tige grêle","Lilas pâle à violet (éperon violet foncé)","Mars–Mai",
                TypeFruit.CAPSULE, ModeDispersion.MYRMECOCHORE,"Mai–Juin",
                "Rhizome court noueux","Éperon violet foncé — distinctif de V. riviniana (éperon clair)"),
            D.ec(2,3,4, 2,3,4, 5.0,6.5,7.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1500, -25.0),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de sous-bois ombragé frais légèrement acide. Chênaies-charmaies et hêtraies."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.FORET_MIXTE),
                listOf("Chênaie-charmaie"), listOf("Carpinion betuli","Fagion")),
            D.dist("Europe tempérée","Commun sauf zones arides"),
            D.phen(listOf(3,4,5), listOf(5,6)),
            Interactions(listOf("Carpinus betulus","Galium odoratum")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("ATHYRIUM_FILIX_FEMINA",
            D.tx("Athyrium filix-femina","(L.) Roth","Athyriaceae","Athyrium","filix-femina","Fougère femelle",
                listOf("Fougère femelle","Athyrium femelle")),
            D.cl(GroupeBiologique.FOUGERE, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Grandes frondes bipennées en touffe étalée","50–150 cm","Grande fougère des lieux frais et ombragés. À distinguer de la Fougère aigle (tripennée).",
                TypeFeuille.COMPOSEE_PENNEE, DispositionFeuille.EN_ROSETTE,
                "Bipennées à pinnules dentées-incisées, rachis vert (non noir). Sores en rein courbé.",
                "Pas de fleurs (sporophyte)","—","—",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Juillet–Août",
                "Rhizome trapu dressé","Sores en forme de fer à cheval — très distinctif"),
            D.ec(3,4,5, 2,3,4, 4.0,5.5,7.0, false, false,
                NiveauLumiere.DEMI_OMBRE, 2000, -30.0,
                listOf("limoneuse humifère")),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de sol frais-humide, acide à légèrement acide, bien aéré. Forêts montagnardes fraîches."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_MIXTE, TypeMilieu.MONTAGNARD), emptyList(),
                listOf("Aulnaie-frênaie","Hêtraie fraîche"), listOf("Alno-Padion","Fagion")),
            D.dist("Eurasie boréale et tempérée","Commun partout hors zones très sèches"),
            D.phen(listOf(5,6,7,8), listOf(7,8)),
            Interactions(listOf("Alnus glutinosa","Fraxinus excelsior")),
            D.if_(RoleForestier.INDICATRICE)),

        // ── HERBACÉES INDICATRICES D'HYDROMORPHIE ─────────────────────────────

        EspeceVegetale("CALTHA_PALUSTRIS",
            D.tx("Caltha palustris","L.","Ranunculaceae","Caltha","palustris","Populage des marais",
                listOf("Souci des marais","Caltha","Grenouillette des marais")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Herbacée charnue à tiges creuses couchées-dressées","20–60 cm","Fleurs jaune d'or très brillantes parmi les premières de l'année. Sol inondé.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Réniformes à cordées, luisantes, bord crénelé. Vert intense.",
                "Fleurs solitaires ou en cymes","Jaune d'or brillant","Mars–Juin",
                TypeFruit.FOLLICULE, ModeDispersion.HYDROCHORE,"Mai–Juillet",
                "Fibreux dense traçant en sol inondé","Sépales pétaloïdes — pas de vrais pétales"),
            D.ec(5,6,7, 3,4,5, 5.5,6.5,7.5, false, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 2000, -30.0),
            D.vi(IndicHumidite.HYGROPHYTE_STRICT, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.NEUTROPHILE,
                hydro=true,
                sig="INDICATEUR FORT d'engorgement quasi-permanent ou d'inondation. Aulnaies, berges, fossés."),
            D.hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Aulnaie ripicole","Mégaphorbiaie"), listOf("Alno-Padion","Calthion")),
            D.dist("Eurasie boréale","Commun partout sur sols engorgés"),
            D.phen(listOf(3,4,5,6), listOf(5,6,7)),
            Interactions(listOf("Alnus glutinosa","Filipendula ulmaria")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("LYSIMACHIA_NUMMULARIA",
            D.tx("Lysimachia nummularia","L.","Primulaceae","Lysimachia","nummularia","Lysimaque nummulaire",
                listOf("Herbe aux écus","Monnayère","Nummulaire")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tiges rampantes indéfiniment, feuilles rondes opposées","tiges 20–60 cm","Couvre-sol rampant de milieux humides. Feuilles rondes distinctives.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Rondes-ovales, base cordée, courts pétioles, vert moyen.",
                "Fleurs axillaires solitaires","Jaune vif","Juin–Août",
                TypeFruit.CAPSULE, ModeDispersion.HYDROCHORE,"Août–Septembre",
                "Tiges rampantes racinantes","Tiges jamais dressées — toujours prostrées"),
            D.ec(4,5,6, 3,4,5, 5.0,6.5,7.5, false, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 1500, -25.0),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.NEUTROPHILE,
                hydro=true,
                sig="Indicateur de sol humide engorgé périodiquement. Bords fossés, berges, aulnaies."),
            D.hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.ZONE_HUMIDE, TypeMilieu.PRAIRIE_FORESTIERE), emptyList()),
            D.dist("Europe et Asie","Commun en plaine et colline sur sols frais-humides"),
            D.phen(listOf(6,7,8), listOf(8,9)),
            Interactions(listOf("Alnus glutinosa","Ranunculus repens")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("RANUNCULUS_REPENS",
            D.tx("Ranunculus repens","L.","Ranunculaceae","Ranunculus","repens","Renoncule rampante",
                listOf("Bouton d'or rampant","Renoncule traçante")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Herbacée à stolons racinants","15–40 cm","Très commune sur tous les sols humides et compactés. Tapis dense en prairie et sous-bois.",
                TypeFeuille.COMPOSEE_PALMATISEE, DispositionFeuille.ALTERNEE,
                "Trilobées, lobes profondément découpés, tache claire sur le lobe central.",
                "Solitaires sur pédoncule sillonné","Jaune brillant","Avril–Octobre",
                TypeFruit.AKENE, ModeDispersion.ZOOCHORE,"Juin–Septembre",
                "Fibreux, stolons racinants","Pédoncule sillonné — distinctif de R. acris"),
            D.ec(4,5,6, 3,4,6, 5.0,6.5,7.5, false, true,
                NiveauLumiere.LUMIERE_PARTIELLE, 2000, -30.0),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.EUTROPHE, IndicAcidite.NEUTROPHILE,
                hydro=true, compac=true,
                sig="INDICATEUR DOUBLE : hydromorphie + compaction. Présence dense = sol engorgé et/ou tassé, nitrophile."),
            D.hab(listOf(TypeMilieu.ZONE_HUMIDE, TypeMilieu.PRAIRIE_FORESTIERE, TypeMilieu.RIPISYLVE),
                listOf(TypeMilieu.MILIEU_PERTURBE, TypeMilieu.CLAIRIERE)),
            D.dist("Eurasie et cosmopolite","Très commun, toute la France"),
            D.phen(listOf(4,5,6,7,8,9,10), listOf(6,7,8,9)),
            Interactions(listOf("Juncus effusus","Rumex obtusifolius")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("CAREX_PENDULA",
            D.tx("Carex pendula","Huds.","Cyperaceae","Carex","pendula","Laîche pendante",
                listOf("Carex à épis pendants","Grande laîche")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Grande touffe de feuilles larges, épis femelles très pendants","80–150 cm","Grande laîche des sous-bois humides. Très reconnaissable à ses longs épis retombants.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Larges (10–18 mm), lisses, brillantes, vert foncé, carène visible.",
                "1–2 épis mâles + 3–5 épis femelles très pendants","Verdâtre","Avril–Juin",
                TypeFruit.AKENE, ModeDispersion.HYDROCHORE,"Juillet–Septembre",
                "Dense fibreux, souche épaisse","Épis femelles très pendants jusqu'à 10–15 cm — très caractéristique"),
            D.ec(4,5,6, 3,4,5, 5.5,6.5,7.5, false, true,
                NiveauLumiere.DEMI_OMBRE, 1200, -20.0,
                listOf("argilo-limoneuse humide")),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.ACIDICLINE,
                hydro=true,
                sig="Indicateur d'aulnaie-frênaie et sous-bois riverains humides. Sol engorgé périodiquement, ombragé."),
            D.hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Aulnaie-frênaie"), listOf("Alno-Ulmion","Alno-Padion")),
            D.dist("Europe atlantique et méditerranéenne","Commun en Ouest et Sud France"),
            D.phen(listOf(4,5,6), listOf(7,8,9)),
            Interactions(listOf("Alnus glutinosa","Fraxinus excelsior","Athyrium filix-femina")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("CIRCAEA_LUTETIANA",
            D.tx("Circaea lutetiana","L.","Onagraceae","Circaea","lutetiana","Circée de Paris",
                listOf("Circée commune","Herbe aux sorcières")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.GEOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Herbacée à tiges dressées, feuilles ovales opposées","30–70 cm","Indicateur emblématique de sol riche et humide ombragé. Fruits accrochants.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Ovales, pointues, base cordée, bord finement denté, légèrement brillantes.",
                "Grappe terminale lâche","Blanc rosé","Juin–Août",
                TypeFruit.AKENE, ModeDispersion.EPIZOOCHORE,"Août–Septembre",
                "Rhizome traçant","Fruits couverts de soies crochues accrochées aux poils et vêtements"),
            D.ec(4,5,6, 4,5,6, 5.5,6.5,7.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1400, -25.0),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.NITROPHILE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de sol frais, riche, ombragé. Forêt riveraine, aulnaie-frênaie, bas de versant."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.RIPISYLVE), emptyList(),
                listOf("Aulnaie-frênaie","Chênaie-charmaie fraîche"), listOf("Alno-Padion","Carpinion")),
            D.dist("Europe et Asie occidentale","Commun sous-bois frais et fertiles"),
            D.phen(listOf(6,7,8), listOf(8,9)),
            Interactions(listOf("Alnus glutinosa","Sambucus nigra")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("IMPATIENS_NOLI_TANGERE",
            D.tx("Impatiens noli-tangere","L.","Balsaminaceae","Impatiens","noli-tangere","Impatiente ne-me-touchez-pas",
                listOf("Balsamine des bois","Impatiente sauvage","Herbe vive")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.THEROPHYTE, StrateVegetale.HERBACEE),
            D.morph("Annuelle charnue translucide, tiges creuses noueuses","30–80 cm","Annuelle des lieux frais et humides. Capsules explosives à maturité.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Ovales, dentées en scie grossière, vert tendre translucide, 5–10 cm.",
                "Grappes de 2–5 fleurs en éperon recourbé","Jaune d'or (tacheté pourpre)","Juillet–Septembre",
                TypeFruit.CAPSULE, ModeDispersion.BAROCHORE,"Août–Octobre",
                "Fibreux superficiel (annuelle)","Capsules explosives au toucher — ecballochorie"),
            D.ec(4,5,6, 4,5,6, 5.5,6.5,7.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1600, -25.0),
            D.vi(IndicHumidite.HYGROPHYTE, IndicFertilite.NITROPHILE, IndicAcidite.NEUTROPHILE,
                sig="Indicateur de bords de ruisseaux, talus frais fertiles ombragés. Forte nitrophilie."),
            D.hab(listOf(TypeMilieu.RIPISYLVE, TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Aulnaie-frênaie"), listOf("Alno-Padion")),
            D.dist("Eurasie boréale et tempérée","Commun hors zones arides"),
            D.phen(listOf(7,8,9), listOf(8,9,10), "Annuelle"),
            Interactions(listOf("Alnus glutinosa","Circaea lutetiana")),
            D.if_(RoleForestier.INDICATRICE)),

        // ── HERBACÉES INDICATRICES DE PERTURBATION / ACIDE ───────────────────

        EspeceVegetale("RUBUS_FRUTICOSUS",
            D.tx("Rubus fruticosus","L. agg.","Rosaceae","Rubus","fruticosus","Ronce commune",
                listOf("Mûrier sauvage","Ronce des bois","Ronce noire")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.NANOPHANEROPHYTE, StrateVegetale.SOUS_ARBUSTE),
            D.morph("Sous-arbuste épineux à tiges arquées souvent penchées","0.5–2 m","Groupe d'agrégation (> 400 microspèces). Colonise toutes les coupes et lisières claires.",
                TypeFeuille.COMPOSEE_PALMATISEE, DispositionFeuille.ALTERNEE,
                "Palmées à 3–5 folioles, vert foncé dessus, blanchâtre dessous, pétiole épineux.",
                "Grappes corymbeuses","Blanc à rose","Juin–Août",
                TypeFruit.POLYDRUPE, ModeDispersion.ZOOCHORE,"Août–Octobre",
                "Souche vivace, drageons nombreux","Tiges bisannuelles : fructification la 2e année"),
            D.ec(2,3,4, 2,3,4, 4.0,5.5,7.0, false, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1500, -25.0),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.ACIDICLINE,
                perturb=true,
                sig="Indicateur de milieu ouvert ou perturbé (coupe, lisière). Colonisation dense = lumière disponible, sol acide à neutre."),
            D.hab(listOf(TypeMilieu.LISIERE, TypeMilieu.CLAIRIERE, TypeMilieu.MILIEU_PERTURBE),
                listOf(TypeMilieu.FORET_FEUILLUE)),
            D.dist("Cosmopolite tempéré","Très commun partout"),
            D.phen(listOf(6,7,8), listOf(8,9,10)),
            Interactions(planteRessourcesFaune = true, planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("EPILOBIUM_ANGUSTIFOLIUM",
            D.tx("Epilobium angustifolium","L.","Onagraceae","Epilobium","angustifolium","Épilobe en épi",
                listOf("Laurier de Saint-Antoine","Épilobe à feuilles étroites","Osier fleuri"),
                listOf("Chamerion angustifolium")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Herbacée dressée formant des colonies denses","60–150 cm","Colonisateur pionnier des coupes forestières et sites incendiés. Fleurs rose vif spectaculaires.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Lancéolées, nervures pennées visibles, alternées, ressemblant au saule (osier).",
                "Longs épis terminaux denses","Rose vif à pourpre","Juillet–Septembre",
                TypeFruit.CAPSULE, ModeDispersion.ANEMOCHORE,"Août–Octobre",
                "Rhizome traçant, drageonnant","Graines à aigrette soyeuse abondante"),
            D.ec(2,3,4, 2,3,5, 4.0,5.5,7.0, false, false,
                NiveauLumiere.PLEIN_SOLEIL, 2200, -35.0),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.ACIDICLINE,
                perturb=true,
                sig="INDICATEUR DE PERTURBATION FORTE (coupe rase, incendie). Colonisation = ouverture récente du milieu."),
            D.hab(listOf(TypeMilieu.CLAIRIERE, TypeMilieu.MILIEU_PERTURBE, TypeMilieu.LISIERE), emptyList()),
            D.dist("Holarctique boréal","Commun hors plaine méridionale aride"),
            D.phen(listOf(7,8,9), listOf(8,9,10)),
            Interactions(listOf("Rubus fruticosus","Betula pendula"), planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("LUZULA_LUZULOIDES",
            D.tx("Luzula luzuloides","(Lam.) Dandy & Wilmott","Juncaceae","Luzula","luzuloides","Luzule blanche",
                listOf("Luzule des bois","Luzule pâle"),
                listOf("Luzula albida")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Petites touffes, feuilles filiformes ciliées à la base","20–50 cm","Graminoïde acide des sous-bois clairs. Inflorescence blanche en glomérules.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Plates étroites 3–5 mm, poils blancs longs sur les bords et gaines.",
                "Cymes composées de glomérules blancs","Blanc à crème","Mai–Juillet",
                TypeFruit.CAPSULE, ModeDispersion.MYRMECOCHORE,"Juillet–Août",
                "Touffes fibreuses","Fleurs blanc crème — à distinguer de L. sylvatica (grande) et L. pilosa"),
            D.ec(2,3,4, 1,1,2, 3.5,4.5,5.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1800, -30.0,
                listOf("sablo-limoneuse acide")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.OLIGOTROPHE, IndicAcidite.ACIDOPHILE,
                sig="INDICATEUR FORT d'acidité et de pauvreté du sol. Chênaies sessiles acides, hêtraies acidiphiles."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.FORET_RESINEUSE), emptyList(),
                listOf("Chênaie sessile acidiphile","Hêtraie acidiphile"), listOf("Luzulo-Quercetum","Luzulo-Fagion")),
            D.dist("Europe centrale et occidentale","Commun massifs acides",
                listOf("Vosges","Ardennes","Massif Central","Bretagne")),
            D.phen(listOf(5,6,7), listOf(7,8)),
            Interactions(listOf("Quercus petraea","Deschampsia flexuosa")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("FESTUCA_HETEROPHYLLA",
            D.tx("Festuca heterophylla","Lam.","Poaceae","Festuca","heterophylla","Fétuque hétérophylle",
                listOf("Fétuque à feuilles variées")),
            D.cl(GroupeBiologique.ANGIOSPERME_MONOCOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Touffes denses, feuilles basales fines, tiges à feuilles plates","40–100 cm","Distinctif : feuilles basales sétacées fines, feuilles caulinaires plates larges.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Dimorphisme foliaire : basales sétacées < 1 mm, caulinaires plates 3–5 mm.",
                "Panicule contractée dressée","Verdâtre","Mai–Juillet",
                TypeFruit.AKENE, ModeDispersion.ANEMOCHORE,"Juillet–Août",
                "Touffes fibreuses","Dimorphisme foliaire caractéristique"),
            D.ec(2,3,4, 2,3,4, 4.5,5.5,6.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1500, -25.0),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHE, IndicAcidite.ACIDICLINE,
                sig="Indicateur de chênaies sessiles acides fraîches. Sous-bois semi-ombragé, sol légèrement acide."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), emptyList(),
                listOf("Chênaie sessile acidiphile"), listOf("Quercion robori-petraeae")),
            D.dist("Europe centro-occidentale","Assez commun massifs siliceux"),
            D.phen(listOf(5,6,7), listOf(7,8)),
            Interactions(listOf("Quercus petraea","Luzula luzuloides")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("GERANIUM_ROBERTIANUM",
            D.tx("Geranium robertianum","L.","Geraniaceae","Geranium","robertianum","Géranium herbe-à-Robert",
                listOf("Herbe à Robert","Géranium de Saint-Robert","Pied-de-corbeau")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.THEROPHYTE, StrateVegetale.HERBACEE),
            D.morph("Annuelle ou bisannuelle à tiges rougeâtres, odeur forte","20–60 cm","Plante très commune des lieux frais et ombragés nitrophiles. Tiges et feuilles souvent rouges.",
                TypeFeuille.COMPOSEE_PALMATISEE, DispositionFeuille.OPPOSEE,
                "Triangulaires bipennées à folioles découpées, souvent rougeâtres à l'automne.",
                "Fleurs solitaires ou par 2","Rose vif","Avril–Octobre",
                TypeFruit.ROSTRATE, ModeDispersion.BAROCHORE,"Juin–Novembre",
                "Pivotant grêle (annuelle)","Odeur forte et un peu désagréable, tiges et fruits rouges"),
            D.ec(3,4,5, 4,5,6, 5.0,6.5,7.5, false, false,
                NiveauLumiere.DEMI_OMBRE, 1800, -20.0),
            D.vi(IndicHumidite.MESOHYGROPHYTE, IndicFertilite.NITROPHILE, IndicAcidite.NEUTROPHILE,
                perturb=true, fert=true,
                sig="Indicateur de sol riche en matière organique, ombragé, frais. Lisières, éboulis, murs — nitrophile."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.LISIERE, TypeMilieu.MILIEU_PERTURBE), emptyList()),
            D.dist("Cosmopolite tempéré","Très commun partout"),
            D.phen(listOf(4,5,6,7,8,9,10), listOf(6,7,8,9,10,11), "Annuelle/bisannuelle"),
            Interactions(listOf("Sambucus nigra","Urtica dioica")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("EUPHORBIA_AMYGDALOIDES",
            D.tx("Euphorbia amygdaloides","L.","Euphorbiaceae","Euphorbia","amygdaloides","Euphorbe des bois",
                listOf("Euphorbe faux-amandier","Tithymale des bois")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.HEMICRYPTOPHYTE, StrateVegetale.HERBACEE),
            D.morph("Tige dressée à feuilles persistantes, latex blanc","30–80 cm","Euphorbe à latex caustique des sous-bois calcaires. Persistent en hiver.",
                TypeFeuille.SIMPLE, DispositionFeuille.ALTERNEE,
                "Oblongues à spatulées, persistantes, vert foncé, base atténuée.",
                "Cyathes jaune-vert en ombelles complexes","Jaune-vert","Mars–Mai",
                TypeFruit.CAPSULE, ModeDispersion.MYRMECOCHORE,"Juin–Juillet",
                "Souche ligneuse pérenne","Latex blanc caustique — toxique"),
            D.ec(2,3,4, 3,4,5, 6.0,7.0,8.0, true, false,
                NiveauLumiere.DEMI_OMBRE, 1200, -20.0,
                listOf("calcaire","argilo-calcaire")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_ELEVEE, IndicAcidite.BASOPHILE,
                sig="Indicateur de sous-bois calcaire semi-ombragé, sol neutre à calcaire. Chênaies-charmaies et hêtraies sur calcaire."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE), listOf(TypeMilieu.LISIERE),
                listOf("Hêtraie calcicole","Chênaie-charmaie calcicole"), listOf("Cephalanthero-Fagion","Carpinion")),
            D.dist("Europe et Méditerranée","Commun sur calcaires sauf extrême Nord"),
            D.phen(listOf(3,4,5), listOf(6,7)),
            Interactions(listOf("Hedera helix","Carpinus betulus")),
            D.if_(RoleForestier.INDICATRICE)),

        EspeceVegetale("LONICERA_PERICLYMENUM",
            D.tx("Lonicera periclymenum","L.","Caprifoliaceae","Lonicera","periclymenum","Chèvrefeuille des bois",
                listOf("Chevrefeuille commun","Vigne des bois","Chèvrefeuille des haies")),
            D.cl(GroupeBiologique.ANGIOSPERME_DICOT, TypeBiologique.PHANEROPHYTE, StrateVegetale.LIANE),
            D.morph("Liane volubile ligneuse, tiges enroulant les arbres","jusqu'à 6 m de hauteur","Liane ligneuse à fleurs très parfumées. Tiges s'enroulent dans le sens des aiguilles d'une montre.",
                TypeFeuille.SIMPLE, DispositionFeuille.OPPOSEE,
                "Ovales-elliptiques, vert dessus, glauque dessous. Paires supérieures non soudées (≠ L. caprifolium).",
                "Capitule terminal de fleurs tubulaires","Blanc-crème virant au jaune","Juin–Août",
                TypeFruit.BAIE, ModeDispersion.ZOOCHORE,"Août–Septembre",
                "Ligneux tortueux, ancré profond","Baies rouge-orange en grappe, toxiques"),
            D.ec(2,3,4, 2,2,3, 4.0,5.0,6.5, false, false,
                NiveauLumiere.LUMIERE_PARTIELLE, 1200, -20.0,
                listOf("sablo-limoneuse","limon acide"), listOf("Atlantique","Océanique")),
            D.vi(IndicHumidite.MESOPHYTE, IndicFertilite.MESOTROPHIE_FAIBLE, IndicAcidite.ACIDOPHILE,
                sig="Indicateur de sol légèrement acide, chênaie sessile ou hêtraie atlantique. Sous-bois semi-ombragé."),
            D.hab(listOf(TypeMilieu.FORET_FEUILLUE, TypeMilieu.LISIERE), emptyList(),
                listOf("Chênaie sessile atlantique"), listOf("Quercion robori-petraeae","Ilici-Fagion")),
            D.dist("Europe atlantique","Commun Ouest et Centre France",
                listOf("Bretagne","Normandie","Pays de la Loire","Sud-Ouest")),
            D.phen(listOf(6,7,8), listOf(8,9), "Liane pérenne"),
            Interactions(planteRessourcesFaune = true, planteMellifere = true),
            D.if_(RoleForestier.INDICATRICE))
    )
}
